applications:
  server:
    source:
      root: "/"
    type: "nodejs:18"
    build:
      flavor: none
    hooks:
      build: |
        # Install server dependencies
        cd server && npm install
        # Build the React client
        cd ../client && npm install --omit=optional && NODE_OPTIONS=--openssl-legacy-provider npm run build
    web:
      commands:
        start: "cd server && node server.js"
      locations:
        "/":
          passthru: true
    mounts:
      "data":
        source: storage
        source_path: data
