// Auto-generated from Rebrickable database
// 2026-04-07T04:55:11.114Z

export const RebrickableCategories = [
  'Baseplates',
  'Bricks Sloped',
  'Bricks Special',
  'Plates Special',
  'Bricks',
  'Plates',
  'Tiles Special',
  'Tiles',
  'Bricks Round and Cones',
  'Plates Round Curved and Dishes',
  'Bricks Curved',
  'Plates Angled',
  'Tiles Round and Curved',
];

export const RebrickableParts = {
  Baseplates: [
    {
      id: '397',
      name: 'Baseplate 10 x 16',
      category: 'Baseplates',
    },
    {
      id: '911b',
      name: 'Baseplate 10 x 48 Train Ferry, 10 x 30 Studs [343-2]',
      category: 'Baseplates',
    },
    {
      id: '911',
      name: 'Baseplate 10 x 48 Train Ferry, Reduced Studs at Center [343-1]',
      category: 'Baseplates',
    },
    {
      id: 'upn0320',
      name: 'Baseplate 14 x 14 Rounded Corners',
      category: 'Baseplates',
    },
    {
      id: 'upn0439',
      name: 'Baseplate 14 x 14 Square Corners',
      category: 'Baseplates',
    },
    {
      id: 'upn0205',
      name: 'Baseplate 14 x 20',
      category: 'Baseplates',
    },
    {
      id: '896',
      name: 'Baseplate 14 x 20 with Rounded Corners [Plain]',
      category: 'Baseplates',
    },
    {
      id: '3867',
      name: 'Baseplate 16 x 16',
      category: 'Baseplates',
    },
    {
      id: '852132board',
      name: 'Baseplate 16 x 16 Castle [Glued to Box]',
      category: 'Baseplates',
    },
    {
      id: '912',
      name: 'Baseplate 16 x 16 Control Tower Set 340',
      category: 'Baseplates',
    },
    {
      id: '51595',
      name: 'Baseplate 16 x 16 Road / Driveway [Plain]',
      category: 'Baseplates',
    },
    {
      id: '184',
      name: 'Baseplate 16 x 18',
      category: 'Baseplates',
    },
    {
      id: '210',
      name: 'Baseplate 16 x 22',
      category: 'Baseplates',
    },
    {
      id: '3334',
      name: 'Baseplate 16 x 24',
      category: 'Baseplates',
    },
    {
      id: '455',
      name: 'Baseplate 16 x 24 with Rounded Corners',
      category: 'Baseplates',
    },
    {
      id: '0904',
      name: 'Baseplate 16 x 24 with Set 080 Large White House Print',
      category: 'Baseplates',
    },
    {
      id: '0903',
      name: 'Baseplate 16 x 24 with Set 080 Red House Print',
      category: 'Baseplates',
    },
    {
      id: '0902',
      name: 'Baseplate 16 x 24 with Set 080 Small White House Print',
      category: 'Baseplates',
    },
    {
      id: '0901',
      name: 'Baseplate 16 x 30 with Set 080 Yellow House Print',
      category: 'Baseplates',
    },
    {
      id: '3857',
      name: 'Baseplate 16 x 32',
      category: 'Baseplates',
    },
  ],
  'Bricks Sloped': [
    {
      id: '30601',
      name: 'Brick Sloped 2 x 2 No Studs with Angled Side Block Extensions',
      category: 'Bricks Sloped',
    },
    {
      id: '7241',
      name: 'Brick Sloped 4 x 4 Corner',
      category: 'Bricks Sloped',
    },
    {
      id: '678',
      name: 'Homemaker Awning 2 x 6',
      category: 'Bricks Sloped',
    },
    {
      id: '3297mib',
      name: 'LEGO PART 3297mib Minitalia Slope 33° 3 x 4 with Bottom Tubes',
      category: 'Bricks Sloped',
    },
    {
      id: '3299mia',
      name: 'Minitalia Slope 33° 2 x 4 Double with Bottom X Supports',
      category: 'Bricks Sloped',
    },
    {
      id: '3298mib',
      name: 'Minitalia Slope 33° 3 x 2 with Bottom Tubes',
      category: 'Bricks Sloped',
    },
    {
      id: '3298mia',
      name: 'Minitalia Slope 33° 3 x 2 with Bottom X Supports',
      category: 'Bricks Sloped',
    },
    {
      id: '3297mia',
      name: 'Minitalia Slope 33° 3 x 4 with Bottom X Supports',
      category: 'Bricks Sloped',
    },
    {
      id: '33215',
      name: 'Roof / Tower 6 x 8 x 9',
      category: 'Bricks Sloped',
    },
    {
      id: '45405',
      name: 'Roof Piece 16 x 4 x 5',
      category: 'Bricks Sloped',
    },
    {
      id: '30614',
      name: 'Roof Piece 6 x 6 x 3 Peaked',
      category: 'Bricks Sloped',
    },
    {
      id: '5654',
      name: 'Slope 1 x 4 with 1 x 2 Cutout',
      category: 'Bricks Sloped',
    },
    {
      id: '4569',
      name: 'Slope 1 x 6 x 1 with 1 x 2 x 1/3 Cutout',
      category: 'Bricks Sloped',
    },
    {
      id: '4515',
      name: 'Slope 10° 6 x 8',
      category: 'Bricks Sloped',
    },
    {
      id: '5404',
      name: 'Slope 18° 2 x 1 x 2/3',
      category: 'Bricks Sloped',
    },
    {
      id: '61409',
      name: 'Slope 18° 2 x 1 x 2/3 with 4 Slots / Grate',
      category: 'Bricks Sloped',
    },
    {
      id: '60477',
      name: 'Slope 18° 4 x 1',
      category: 'Bricks Sloped',
    },
    {
      id: '30363',
      name: 'Slope 18° 4 x 2',
      category: 'Bricks Sloped',
    },
    {
      id: '30603',
      name: 'Slope 2 x 2 No Studs, with 3 Side Pistons Raised Edges',
      category: 'Bricks Sloped',
    },
    {
      id: '49618',
      name: 'Slope 25° 1 x 8 x 3',
      category: 'Bricks Sloped',
    },
  ],
  'Bricks Special': [
    {
      id: '30585a',
      name: 'Aero Tube Joiner 2 x 4 x 3',
      category: 'Bricks Special',
    },
    {
      id: '30585b',
      name: 'Aero Tube Joiner 3 x 4 x 3',
      category: 'Bricks Special',
    },
    {
      id: '47993',
      name: 'Boat Deck Brick 8 x 3 x 4 Railing',
      category: 'Bricks Special',
    },
    {
      id: '73562',
      name: 'Bracket 3 x 2 x 1 1/3 with Bottom Stud Holder',
      category: 'Bricks Special',
    },
    {
      id: '18671',
      name: 'Bracket 3 x 2 x 1 1/3 with Pin Bottom',
      category: 'Bricks Special',
    },
    {
      id: '5712',
      name: 'Bracket 5 x 1 x 1 1/3',
      category: 'Bricks Special',
    },
    {
      id: '79180',
      name: 'Bracket 5 x 2 x 1 1/3 with Bottom Stud Holder',
      category: 'Bricks Special',
    },
    {
      id: '11215',
      name: 'Bracket 5 x 2 x 1 1/3 with Holes, Pin Bottom',
      category: 'Bricks Special',
    },
    {
      id: '76766',
      name: 'Bracket 5 x 2 x 2 1/3 with Holes, Inside Stud Holder',
      category: 'Bricks Special',
    },
    {
      id: '6087',
      name: 'Bracket 5 x 2 x 2 1/3 with Holes, Smooth Bottom',
      category: 'Bricks Special',
    },
    {
      id: '4732',
      name: 'Bracket 8 x 2 x 1 1/3',
      category: 'Bricks Special',
    },
    {
      id: '60189',
      name: 'Braille Brick 2 x 4 with 1 Stud ⠁',
      category: 'Bricks Special',
    },
    {
      id: '65552',
      name: 'Braille Brick 2 x 4 with 1 Stud ⠂',
      category: 'Bricks Special',
    },
    {
      id: '65551',
      name: 'Braille Brick 2 x 4 with 1 Stud ⠄',
      category: 'Bricks Special',
    },
    {
      id: '65559',
      name: 'Braille Brick 2 x 4 with 1 Stud ⠐',
      category: 'Bricks Special',
    },
    {
      id: '65557',
      name: 'Braille Brick 2 x 4 with 1 Studs ⠠',
      category: 'Bricks Special',
    },
    {
      id: '60190',
      name: 'Braille Brick 2 x 4 with 2 Studs ⠃',
      category: 'Bricks Special',
    },
    {
      id: '60225',
      name: 'Braille Brick 2 x 4 with 2 Studs ⠅',
      category: 'Bricks Special',
    },
    {
      id: '60191',
      name: 'Braille Brick 2 x 4 with 2 Studs ⠉',
      category: 'Bricks Special',
    },
    {
      id: '60223',
      name: 'Braille Brick 2 x 4 with 2 Studs ⠊',
      category: 'Bricks Special',
    },
  ],
  'Plates Special': [
    {
      id: '36841',
      name: 'Bracket 1 x 1 - 1 x 1',
      category: 'Plates Special',
    },
    {
      id: '36840',
      name: 'Bracket 1 x 1 - 1 x 1 Inverted',
      category: 'Plates Special',
    },
    {
      id: '79389',
      name: 'Bracket 1 x 1 - 1 x 2',
      category: 'Plates Special',
    },
    {
      id: '73825',
      name: 'Bracket 1 x 1 - 1 x 2 Inverted',
      category: 'Plates Special',
    },
    {
      id: '99781',
      name: 'Bracket 1 x 2 - 1 x 2',
      category: 'Plates Special',
    },
    {
      id: '99780',
      name: 'Bracket 1 x 2 - 1 x 2 Inverted',
      category: 'Plates Special',
    },
    {
      id: '28802',
      name: 'Bracket 1 x 2 - 1 x 4 [Rounded Corners at Bottom, Square Corners at Top]',
      category: 'Plates Special',
    },
    {
      id: '10201',
      name: 'Bracket 1 x 2 - 1 x 4 [Rounded Corners]',
      category: 'Plates Special',
    },
    {
      id: '2436',
      name: 'Bracket 1 x 2 - 1 x 4 [Square Corners]',
      category: 'Plates Special',
    },
    {
      id: '44728',
      name: 'Bracket 1 x 2 - 2 x 2',
      category: 'Plates Special',
    },
    {
      id: '7674',
      name: 'Bracket 1 x 2 - 2 x 2 Centered',
      category: 'Plates Special',
    },
    {
      id: '99207',
      name: 'Bracket 1 x 2 - 2 x 2 Inverted',
      category: 'Plates Special',
    },
    {
      id: '93274',
      name: 'Bracket 1 x 2 - 2 x 4',
      category: 'Plates Special',
    },
    {
      id: '7452',
      name: 'Bracket 1 x 2 - 2 x 4 Inverted',
      category: 'Plates Special',
    },
    {
      id: '6970',
      name: 'Bracket 1 x 2 - 2 x 6',
      category: 'Plates Special',
    },
    {
      id: '4585',
      name: 'Bracket 1 x 2 with 1 x 2 Vertical Studs',
      category: 'Plates Special',
    },
    {
      id: '5090',
      name: 'Bracket 1 x 6 - 2 x 6 Inverted',
      category: 'Plates Special',
    },
    {
      id: '3956',
      name: 'Bracket 2 x 2 - 2 x 2',
      category: 'Plates Special',
    },
    {
      id: '41682',
      name: 'Bracket 2 x 2 with 1 x 2 Vertical Studs',
      category: 'Plates Special',
    },
    {
      id: '69906',
      name: 'Bracket 2 x 3 - 2 x 2, Curved Sides',
      category: 'Plates Special',
    },
  ],
  Bricks: [
    {
      id: '3005',
      name: 'Brick 1 x 1',
      category: 'Bricks',
    },
    {
      id: '14716',
      name: 'Brick 1 x 1 x 3',
      category: 'Bricks',
    },
    {
      id: '2453a',
      name: 'Brick 1 x 1 x 5 with Blocked Open or Hollow Stud',
      category: 'Bricks',
    },
    {
      id: '2453b',
      name: 'Brick 1 x 1 x 5 with Solid Stud',
      category: 'Bricks',
    },
    {
      id: '6111',
      name: 'Brick 1 x 10',
      category: 'Bricks',
    },
    {
      id: '6112',
      name: 'Brick 1 x 12',
      category: 'Bricks',
    },
    {
      id: '2465',
      name: 'Brick 1 x 16',
      category: 'Bricks',
    },
    {
      id: '3004',
      name: 'Brick 1 x 2',
      category: 'Bricks',
    },
    {
      id: '3065a',
      name: 'Brick 1 x 2 with 2 Slots',
      category: 'Bricks',
    },
    {
      id: '3065',
      name: 'Brick 1 x 2 without Bottom Tube',
      category: 'Bricks',
    },
    {
      id: '3065b',
      name: 'Brick 1 x 2 without Bottom Tube, Slotted (with 1 slot)',
      category: 'Bricks',
    },
    {
      id: '3245a',
      name: 'Brick 1 x 2 x 2 with Center Pin [Plain]',
      category: 'Bricks',
    },
    {
      id: '3245b',
      name: 'Brick 1 x 2 x 2 with Inside Axle Holder',
      category: 'Bricks',
    },
    {
      id: '3245c',
      name: 'Brick 1 x 2 x 2 with Inside Stud Holder',
      category: 'Bricks',
    },
    {
      id: '772',
      name: 'Brick 1 x 2 x 2 without Bottom Tube',
      category: 'Bricks',
    },
    {
      id: '22886',
      name: 'Brick 1 x 2 x 3 with Bottom Stud Holder',
      category: 'Bricks',
    },
    {
      id: '2454a',
      name: 'Brick 1 x 2 x 5 with Blocked Open Studs and Bottom Stud Holder with Asymmetric Ridges',
      category: 'Bricks',
    },
    {
      id: '2454b',
      name: 'Brick 1 x 2 x 5 with Hollow Studs',
      category: 'Bricks',
    },
    {
      id: '46212',
      name: 'Brick 1 x 2 x 5 without Side Supports',
      category: 'Bricks',
    },
    {
      id: '3622',
      name: 'Brick 1 x 3',
      category: 'Bricks',
    },
  ],
  Plates: [
    {
      id: '3024',
      name: 'Plate 1 x 1',
      category: 'Plates',
    },
    {
      id: '86996',
      name: 'Plate 1 x 1 x 2/3 with Open Stud',
      category: 'Plates',
    },
    {
      id: '4477',
      name: 'Plate 1 x 10',
      category: 'Plates',
    },
    {
      id: '60479',
      name: 'Plate 1 x 12',
      category: 'Plates',
    },
    {
      id: '3023',
      name: 'Plate 1 x 2',
      category: 'Plates',
    },
    {
      id: '3023a',
      name: 'Plate 1 x 2 [Old Style Bottom]',
      category: 'Plates',
    },
    {
      id: '3623',
      name: 'Plate 1 x 3',
      category: 'Plates',
    },
    {
      id: '3710',
      name: 'Plate 1 x 4',
      category: 'Plates',
    },
    {
      id: '78329',
      name: 'Plate 1 x 5',
      category: 'Plates',
    },
    {
      id: '3666',
      name: 'Plate 1 x 6',
      category: 'Plates',
    },
    {
      id: '3460',
      name: 'Plate 1 x 8',
      category: 'Plates',
    },
    {
      id: '91405',
      name: 'Plate 16 x 16',
      category: 'Plates',
    },
    {
      id: '3832',
      name: 'Plate 2 x 10',
      category: 'Plates',
    },
    {
      id: '2445',
      name: 'Plate 2 x 12',
      category: 'Plates',
    },
    {
      id: '91988',
      name: 'Plate 2 x 14',
      category: 'Plates',
    },
    {
      id: '4282',
      name: 'Plate 2 x 16',
      category: 'Plates',
    },
    {
      id: '3022',
      name: 'Plate 2 x 2',
      category: 'Plates',
    },
    {
      id: '2420',
      name: 'Plate 2 x 2 Corner',
      category: 'Plates',
    },
    {
      id: '3021',
      name: 'Plate 2 x 3',
      category: 'Plates',
    },
    {
      id: '73831',
      name: 'Plate 2 x 3 with 1 x 1 Cutout',
      category: 'Plates',
    },
  ],
  'Tiles Special': [
    {
      id: '107428',
      name: 'FLAT TILE 2X3, W/ ANGLE, NO. 146',
      category: 'Tiles Special',
    },
    {
      id: '70942',
      name: 'Tile 1 x 2 with Ball',
      category: 'Tiles Special',
    },
    {
      id: '5091',
      name: 'Tile 1 x 2 with Stud Notch Left',
      category: 'Tiles Special',
    },
    {
      id: '5092',
      name: 'Tile 1 x 2 with Stud Notch Right',
      category: 'Tiles Special',
    },
    {
      id: '74169',
      name: 'Tile 3 x 4 x 2/3 Mickey Mouse',
      category: 'Tiles Special',
    },
    {
      id: '35787',
      name: 'Tile 45° Cut 2 x 2 (Triangle)',
      category: 'Tiles Special',
    },
    {
      id: '3160',
      name: 'Tile 6 x 6 x 2/3, Angled Textured Surface (Ice)',
      category: 'Tiles Special',
    },
    {
      id: '77813',
      name: 'Tile Round 1 x 1 Special with Clip-Bar',
      category: 'Tiles Special',
    },
    {
      id: '20482',
      name: 'Tile Round 1 x 1 with Hollow Bar',
      category: 'Tiles Special',
    },
    {
      id: '74698',
      name: 'Tile Round 2 x 2 - Thick Lifting Ring',
      category: 'Tiles Special',
    },
    {
      id: '2376',
      name: 'Tile Round 2 x 2 - Thin Lifting Ring',
      category: 'Tiles Special',
    },
    {
      id: '15535',
      name: 'Tile Round 2 x 2 with Hole',
      category: 'Tiles Special',
    },
    {
      id: '2555',
      name: 'Tile Special 1 x 1 with Clip and Straight Tips',
      category: 'Tiles Special',
    },
    {
      id: '15712',
      name: 'Tile Special 1 x 1 with Clip with Rounded Edges',
      category: 'Tiles Special',
    },
    {
      id: '12825',
      name: 'Tile Special 1 x 1 with Clip with Rounded Tips',
      category: 'Tiles Special',
    },
    {
      id: '93794',
      name: 'Tile Special 1 x 1 with Clip with Rounded Tips and Center Cut',
      category: 'Tiles Special',
    },
    {
      id: '72078pat0001',
      name: 'Tile Special 1 x 1 with Molded Opal Trans-Clear Diamond',
      category: 'Tiles Special',
    },
    {
      id: '35649',
      name: 'Tile Special 1 x 2 Diamond Plain',
      category: 'Tiles Special',
    },
    {
      id: '2412b',
      name: 'Tile Special 1 x 2 Grille with Bottom Groove',
      category: 'Tiles Special',
    },
    {
      id: '2412a',
      name: 'Tile Special 1 x 2 Grille without Bottom Groove',
      category: 'Tiles Special',
    },
  ],
  Tiles: [
    {
      id: '66404',
      name: 'FLAT TILE 1X1, NO. 269',
      category: 'Tiles',
    },
    {
      id: '101651',
      name: 'FLAT TILE 1X1, NO. 282',
      category: 'Tiles',
    },
    {
      id: '101652',
      name: 'FLAT TILE 1X1, NO. 283',
      category: 'Tiles',
    },
    {
      id: '101653',
      name: 'FLAT TILE 1X1, NO. 284',
      category: 'Tiles',
    },
    {
      id: '101654',
      name: 'FLAT TILE 1X1, NO. 285',
      category: 'Tiles',
    },
    {
      id: '101655',
      name: 'FLAT TILE 1X1, NO. 286',
      category: 'Tiles',
    },
    {
      id: '101645',
      name: 'FLAT TILE 1X1, NO. 287',
      category: 'Tiles',
    },
    {
      id: '103033',
      name: 'FLAT TILE 1X1, NO. 292',
      category: 'Tiles',
    },
    {
      id: '103035',
      name: 'FLAT TILE 1X1, NO. 294',
      category: 'Tiles',
    },
    {
      id: '78171',
      name: 'FLAT TILE 2X2, NO. 500',
      category: 'Tiles',
    },
    {
      id: '3070b',
      name: 'Tile 1 x 1 with Groove',
      category: 'Tiles',
    },
    {
      id: '3070a',
      name: 'Tile 1 x 1 without Groove',
      category: 'Tiles',
    },
    {
      id: '67211',
      name: 'Tile 1 x 1, Random DOTS Series 2 Print',
      category: 'Tiles',
    },
    {
      id: '73002',
      name: 'Tile 1 x 1, Random DOTS Series 3 Print',
      category: 'Tiles',
    },
    {
      id: '3069b',
      name: 'Tile 1 x 2 with Groove',
      category: 'Tiles',
    },
    {
      id: '3069a',
      name: 'Tile 1 x 2 without Groove',
      category: 'Tiles',
    },
    {
      id: '63864',
      name: 'Tile 1 x 3',
      category: 'Tiles',
    },
    {
      id: '2431',
      name: 'Tile 1 x 4 with Groove',
      category: 'Tiles',
    },
    {
      id: '6636',
      name: 'Tile 1 x 6 with Groove',
      category: 'Tiles',
    },
    {
      id: '4162',
      name: 'Tile 1 x 8 with Groove',
      category: 'Tiles',
    },
  ],
  'Bricks Round and Cones': [
    {
      id: '5692',
      name: 'Ball with Ears',
      category: 'Bricks Round and Cones',
    },
    {
      id: '7324',
      name: 'Brick Round 1 x 1 D. Tube with 45° Elbow and Axle Holes (Crossholes) at Each End',
      category: 'Bricks Round and Cones',
    },
    {
      id: '71076',
      name: 'Brick Round 1 x 1 diameter Tube with 90 Degree Elbow (2 x 2 x 1)',
      category: 'Bricks Round and Cones',
    },
    {
      id: '25214',
      name: 'Brick Round 1 x 1 diameter Tube with 90 Degree Elbow (2 x 2 x 1) and Axle Holes (Crossholes) at each end',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3062b',
      name: 'Brick Round 1 x 1 Open Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3062a',
      name: 'Brick Round 1 x 1 Solid Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3062c',
      name: 'Brick Round 1 x 1 Solid Stud, No Bottom Groove',
      category: 'Bricks Round and Cones',
    },
    {
      id: '6331',
      name: 'Brick Round 1 x 1 with 3 Bars',
      category: 'Bricks Round and Cones',
    },
    {
      id: '4588',
      name: 'Brick Round 1 x 1 with Fins, Open Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '71075',
      name: 'Brick Round 1 x 1 x 1 2/3',
      category: 'Bricks Round and Cones',
    },
    {
      id: '4770',
      name: 'Brick Round 1 x 1 x 2/3 Light Bulb Cover',
      category: 'Bricks Round and Cones',
    },
    {
      id: '20952',
      name: 'Brick Round 1.5 x 1.5 Dome Top [Plain]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '92947',
      name: 'Brick Round 2 x 2 [Grill]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5489',
      name: 'Brick Round 2 x 2 D. Tube with 45° Elbow and Axle Holes (Crossholes) at Each End [LONG]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '65473',
      name: 'Brick Round 2 x 2 D. Tube with 45° Elbow and Axle Holes (Crossholes) at Each End [SHORT]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '15395',
      name: 'Brick Round 2 x 2 Dome Bottom [Open Stud]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5690',
      name: 'Brick Round 2 x 2 Dome Top with 2 Ears',
      category: 'Bricks Round and Cones',
    },
    {
      id: '30367b',
      name: 'Brick Round 2 x 2 Dome Top, Blocked Open Stud, Bottom Axle Holder',
      category: 'Bricks Round and Cones',
    },
    {
      id: '30367a',
      name: 'Brick Round 2 x 2 Dome Top, Blocked Open Stud, No Bottom Axle Holder',
      category: 'Bricks Round and Cones',
    },
    {
      id: '30367c',
      name: 'Brick Round 2 x 2 Dome Top, Hollow Stud',
      category: 'Bricks Round and Cones',
    },
  ],
  'Plates Round Curved and Dishes': [
    {
      id: '7688',
      name: 'Disc Oval 4 x 6',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '50990a',
      name: 'Dish 10 x 10 Inverted (Radar) with Hollow Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '50990b',
      name: 'Dish 10 x 10 Inverted (Radar) with Solid Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4740',
      name: 'Dish 2 x 2 Inverted [Radar]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '6919',
      name: 'Dish 2 x 2 with Angled Bar',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '71128',
      name: 'Dish 2 x 2 x 2/3 Light Reflector',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '43898',
      name: 'Dish 3 x 3 Inverted [Radar]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '3960',
      name: 'Dish 4 x 4 Inverted [Radar]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '35394',
      name: 'Dish 4 x 4 Inverted with Open Stud [Radar]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '65138',
      name: 'Dish 4 x 4 with 4 Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '6942',
      name: 'Dish 5 x 5',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '44375a',
      name: 'Dish 6 x 6 Inverted (Radar) with Hollow Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '44375b',
      name: 'Dish 6 x 6 Inverted (Radar) with Solid Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4285b',
      name: 'Dish 6 x 6 Inverted, Radar / Webbed [Anti-studs at 90°]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4285a',
      name: 'Dish 6 x 6 Inverted, Radar / Webbed [No Anti-studs]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '18859',
      name: 'Dish 8 x 8 Inverted [Radar], Hollow Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '3961',
      name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Rounded Anti-stud Underside',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '3961a',
      name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Squared Anti-stud Underside',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '35154',
      name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Squared Anti-stud Underside, Anti-Studs on Edges',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '98606',
      name: 'Dish 9 x 9 Inverted with Pin Hole (Radar)',
      category: 'Plates Round Curved and Dishes',
    },
  ],
  'Bricks Curved': [
    {
      id: '6108',
      name: 'Brick Arch 1 x 12 x 3',
      category: 'Bricks Curved',
    },
    {
      id: '14707',
      name: 'Brick Arch 1 x 12 x 3 Raised Arch',
      category: 'Bricks Curved',
    },
    {
      id: '18838',
      name: 'Brick Arch 1 x 12 x 3 Raised Arch with 5 Cross Supports',
      category: 'Bricks Curved',
    },
    {
      id: '6184',
      name: 'Brick Arch 1 x 12 x 5 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '4490',
      name: 'Brick Arch 1 x 3',
      category: 'Bricks Curved',
    },
    {
      id: '5843',
      name: 'Brick Arch 1 x 3 x 1 2/3 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '88292',
      name: 'Brick Arch 1 x 3 x 2',
      category: 'Bricks Curved',
    },
    {
      id: '6005',
      name: 'Brick Arch 1 x 3 x 2 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '18653',
      name: 'Brick Arch 1 x 3 x 2 Inverted [Inside Bow]',
      category: 'Bricks Curved',
    },
    {
      id: '5850',
      name: 'Brick Arch 1 x 3 x 2, Straight End',
      category: 'Bricks Curved',
    },
    {
      id: '13965',
      name: 'Brick Arch 1 x 3 x 3 [Gothic]',
      category: 'Bricks Curved',
    },
    {
      id: '3659',
      name: 'Brick Arch 1 x 4',
      category: 'Bricks Curved',
    },
    {
      id: '6182',
      name: 'Brick Arch 1 x 4 x 2',
      category: 'Bricks Curved',
    },
    {
      id: '5844',
      name: 'Brick Arch 1 x 4 x 2 1/3 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '80543',
      name: 'Brick Arch 1 x 4 x 3',
      category: 'Bricks Curved',
    },
    {
      id: '3572',
      name: 'Brick Arch 1 x 5 x 2',
      category: 'Bricks Curved',
    },
    {
      id: '5845',
      name: 'Brick Arch 1 x 5 x 3 1/3 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '14395',
      name: 'Brick Arch 1 x 5 x 4 [Continuous Bow, Raised Underside Cross Supports]',
      category: 'Bricks Curved',
    },
    {
      id: '2339',
      name: 'Brick Arch 1 x 5 x 4 [Continuous Bow]',
      category: 'Bricks Curved',
    },
    {
      id: '76768',
      name: 'Brick Arch 1 x 5 x 4 [Irregular Bow, Raised Underside Cross Supports]',
      category: 'Bricks Curved',
    },
  ],
  'Plates Angled': [
    {
      id: '79846',
      name: 'Plate Angled 2 x 2 with Step and Hole in Center',
      category: 'Plates Angled',
    },
    {
      id: '44666',
      name: 'Plate Angles Hexagonal 14 X 18',
      category: 'Plates Angled',
    },
    {
      id: '92584',
      name: 'Wedge Plate 10 x 10 Cut Corner [No Centre Studs]',
      category: 'Plates Angled',
    },
    {
      id: '2401',
      name: 'Wedge Plate 10 x 10 with 4x4 Cutout and Cut Corner',
      category: 'Plates Angled',
    },
    {
      id: '47397',
      name: 'Wedge Plate 12 x 3 Left',
      category: 'Plates Angled',
    },
    {
      id: '47398',
      name: 'Wedge Plate 12 x 3 Right',
      category: 'Plates Angled',
    },
    {
      id: '26601',
      name: 'Wedge Plate 2 x 2 Cut Corner',
      category: 'Plates Angled',
    },
    {
      id: '24299',
      name: 'Wedge Plate 2 x 2 Left',
      category: 'Plates Angled',
    },
    {
      id: '24307',
      name: 'Wedge Plate 2 x 2 Right',
      category: 'Plates Angled',
    },
    {
      id: '51739',
      name: 'Wedge Plate 2 x 4',
      category: 'Plates Angled',
    },
    {
      id: '65429',
      name: 'Wedge Plate 2 x 4 27° Left',
      category: 'Plates Angled',
    },
    {
      id: '65426',
      name: 'Wedge Plate 2 x 4 27° Right',
      category: 'Plates Angled',
    },
    {
      id: '43723',
      name: 'Wedge Plate 3 x 2 Left',
      category: 'Plates Angled',
    },
    {
      id: '43722',
      name: 'Wedge Plate 3 x 2 Right',
      category: 'Plates Angled',
    },
    {
      id: '2450',
      name: 'Wedge Plate 3 x 3 Cut Corner',
      category: 'Plates Angled',
    },
    {
      id: '48183',
      name: 'Wedge Plate 3 x 4 with Stud Notches',
      category: 'Plates Angled',
    },
    {
      id: '90194',
      name: 'Wedge Plate 3 x 4 with Stud Notches [Reinforced Underside]',
      category: 'Plates Angled',
    },
    {
      id: '4859',
      name: 'Wedge Plate 3 x 4 without Stud Notches',
      category: 'Plates Angled',
    },
    {
      id: '2419',
      name: 'Wedge Plate 3 x 6 Cut Corners',
      category: 'Plates Angled',
    },
    {
      id: '15706',
      name: 'Wedge Plate 4 Stud 45° Angle Plate',
      category: 'Plates Angled',
    },
  ],
  'Tiles Round and Curved': [
    {
      id: '83079',
      name: 'FLAT TILE 1X1, ROUND, NO. 184',
      category: 'Tiles Round and Curved',
    },
    {
      id: '83085',
      name: 'FLAT TILE 1X1, ROUND, NO. 208',
      category: 'Tiles Round and Curved',
    },
    {
      id: '39739',
      name: 'Tile 1 x 1 Heart',
      category: 'Tiles Round and Curved',
    },
    {
      id: '27925',
      name: 'Tile 2 x 2 Curved, Macaroni',
      category: 'Tiles Round and Curved',
    },
    {
      id: '7836',
      name: 'Tile 2 x 2 Curved, Macaroni, Center Anti-Stud',
      category: 'Tiles Round and Curved',
    },
    {
      id: '79393',
      name: 'Tile 3 x 3 Curved, Macaroni',
      category: 'Tiles Round and Curved',
    },
    {
      id: '27507',
      name: 'Tile 4 x 4 Curved, Macaroni',
      category: 'Tiles Round and Curved',
    },
    {
      id: '65474',
      name: 'Tile 6 x 8 with Rounded Corners',
      category: 'Tiles Round and Curved',
    },
    {
      id: '73099',
      name: 'Tile Pack 1 x 1 Half Circle, Random DOTS Series 4 Print',
      category: 'Tiles Round and Curved',
    },
    {
      id: '77486',
      name: 'Tile Pack 169 - Letters',
      category: 'Tiles Round and Curved',
    },
    {
      id: '83152',
      name: 'Tile Pack for 41949-1',
      category: 'Tiles Round and Curved',
    },
    {
      id: '66402',
      name: 'Tile Pack for 41957-1',
      category: 'Tiles Round and Curved',
    },
    {
      id: '98138',
      name: 'Tile Round 1 x 1',
      category: 'Tiles Round and Curved',
    },
    {
      id: '24246',
      name: 'Tile Round 1 x 1 Half Circle',
      category: 'Tiles Round and Curved',
    },
    {
      id: '25269',
      name: 'Tile Round 1 x 1 Quarter',
      category: 'Tiles Round and Curved',
    },
    {
      id: '67222',
      name: 'Tile Round 1 x 1 Random DOTS Series 1 Print',
      category: 'Tiles Round and Curved',
    },
    {
      id: '72046pat0001',
      name: 'Tile Round 1 x 1 with Molded Trans-Bright Pink Star',
      category: 'Tiles Round and Curved',
    },
    {
      id: '72046pat0002',
      name: 'Tile Round 1 x 1 with Molded Trans-Dark Blue Star',
      category: 'Tiles Round and Curved',
    },
    {
      id: '67216',
      name: 'Tile Round 1 x 1, Random DOTS Mega Pack 1 Print',
      category: 'Tiles Round and Curved',
    },
    {
      id: '67217',
      name: 'Tile Round 1 x 1, Random DOTS Mega Pack 2 Print',
      category: 'Tiles Round and Curved',
    },
  ],
};

export const RebrickableColors = [
  {
    id: '0',
    name: 'Black',
    rgb: '05131D',
  },
  {
    id: '15',
    name: 'White',
    rgb: 'FFFFFF',
  },
  {
    id: '71',
    name: 'Light Bluish Gray',
    rgb: 'A0A5A9',
  },
  {
    id: '72',
    name: 'Dark Bluish Gray',
    rgb: '6C6E68',
  },
  {
    id: '4',
    name: 'Red',
    rgb: 'C91A09',
  },
  {
    id: '14',
    name: 'Yellow',
    rgb: 'F2CD37',
  },
  {
    id: '1',
    name: 'Blue',
    rgb: '0055BF',
  },
  {
    id: '19',
    name: 'Tan',
    rgb: 'E4CD9E',
  },
  {
    id: '70',
    name: 'Reddish Brown',
    rgb: '582A12',
  },
  {
    id: '7',
    name: 'Light Gray',
    rgb: '9BA19D',
  },
  {
    id: '2',
    name: 'Green',
    rgb: '237841',
  },
  {
    id: '28',
    name: 'Dark Tan',
    rgb: '958A73',
  },
  {
    id: '25',
    name: 'Orange',
    rgb: 'FE8A18',
  },
  {
    id: '272',
    name: 'Dark Blue',
    rgb: '0A3463',
  },
  {
    id: '297',
    name: 'Pearl Gold',
    rgb: 'AA7F2E',
  },
  {
    id: '320',
    name: 'Dark Red',
    rgb: '720E0F',
  },
  {
    id: '27',
    name: 'Lime',
    rgb: 'BBE90B',
  },
  {
    id: '84',
    name: 'Medium Nougat',
    rgb: 'AA7D55',
  },
  {
    id: '191',
    name: 'Bright Light Orange',
    rgb: 'F8BB3D',
  },
  {
    id: '322',
    name: 'Medium Azure',
    rgb: '36AEBF',
  },
  {
    id: '484',
    name: 'Dark Orange',
    rgb: 'A95500',
  },
  {
    id: '10',
    name: 'Bright Green',
    rgb: '4B9F4A',
  },
  {
    id: '288',
    name: 'Dark Green',
    rgb: '184632',
  },
  {
    id: '378',
    name: 'Sand Green',
    rgb: 'A0BCAC',
  },
  {
    id: '308',
    name: 'Dark Brown',
    rgb: '352100',
  },
  {
    id: '3',
    name: 'Dark Turquoise',
    rgb: '008F9B',
  },
  {
    id: '179',
    name: 'Flat Silver',
    rgb: '898788',
  },
  {
    id: '8',
    name: 'Dark Gray',
    rgb: '6D6E5C',
  },
  {
    id: '29',
    name: 'Bright Pink',
    rgb: 'E4ADC8',
  },
  {
    id: '85',
    name: 'Dark Purple',
    rgb: '3F3691',
  },
];

export const RebrickablePartsFlat = [
  { id: '397', name: 'Baseplate 10 x 16', category: 'Baseplates' },
  {
    id: '911b',
    name: 'Baseplate 10 x 48 Train Ferry, 10 x 30 Studs [343-2]',
    category: 'Baseplates',
  },
  {
    id: '911',
    name: 'Baseplate 10 x 48 Train Ferry, Reduced Studs at Center [343-1]',
    category: 'Baseplates',
  },
  { id: 'upn0320', name: 'Baseplate 14 x 14 Rounded Corners', category: 'Baseplates' },
  { id: 'upn0439', name: 'Baseplate 14 x 14 Square Corners', category: 'Baseplates' },
  { id: 'upn0205', name: 'Baseplate 14 x 20', category: 'Baseplates' },
  { id: '896', name: 'Baseplate 14 x 20 with Rounded Corners [Plain]', category: 'Baseplates' },
  { id: '3867', name: 'Baseplate 16 x 16', category: 'Baseplates' },
  { id: '852132board', name: 'Baseplate 16 x 16 Castle [Glued to Box]', category: 'Baseplates' },
  { id: '912', name: 'Baseplate 16 x 16 Control Tower Set 340', category: 'Baseplates' },
  { id: '51595', name: 'Baseplate 16 x 16 Road / Driveway [Plain]', category: 'Baseplates' },
  { id: '184', name: 'Baseplate 16 x 18', category: 'Baseplates' },
  { id: '210', name: 'Baseplate 16 x 22', category: 'Baseplates' },
  { id: '3334', name: 'Baseplate 16 x 24', category: 'Baseplates' },
  { id: '455', name: 'Baseplate 16 x 24 with Rounded Corners', category: 'Baseplates' },
  {
    id: '0904',
    name: 'Baseplate 16 x 24 with Set 080 Large White House Print',
    category: 'Baseplates',
  },
  { id: '0903', name: 'Baseplate 16 x 24 with Set 080 Red House Print', category: 'Baseplates' },
  {
    id: '0902',
    name: 'Baseplate 16 x 24 with Set 080 Small White House Print',
    category: 'Baseplates',
  },
  { id: '0901', name: 'Baseplate 16 x 30 with Set 080 Yellow House Print', category: 'Baseplates' },
  { id: '3857', name: 'Baseplate 16 x 32', category: 'Baseplates' },
  {
    id: '30601',
    name: 'Brick Sloped 2 x 2 No Studs with Angled Side Block Extensions',
    category: 'Bricks Sloped',
  },
  { id: '7241', name: 'Brick Sloped 4 x 4 Corner', category: 'Bricks Sloped' },
  { id: '678', name: 'Homemaker Awning 2 x 6', category: 'Bricks Sloped' },
  {
    id: '3297mib',
    name: 'LEGO PART 3297mib Minitalia Slope 33° 3 x 4 with Bottom Tubes',
    category: 'Bricks Sloped',
  },
  {
    id: '3299mia',
    name: 'Minitalia Slope 33° 2 x 4 Double with Bottom X Supports',
    category: 'Bricks Sloped',
  },
  { id: '3298mib', name: 'Minitalia Slope 33° 3 x 2 with Bottom Tubes', category: 'Bricks Sloped' },
  {
    id: '3298mia',
    name: 'Minitalia Slope 33° 3 x 2 with Bottom X Supports',
    category: 'Bricks Sloped',
  },
  {
    id: '3297mia',
    name: 'Minitalia Slope 33° 3 x 4 with Bottom X Supports',
    category: 'Bricks Sloped',
  },
  { id: '33215', name: 'Roof / Tower 6 x 8 x 9', category: 'Bricks Sloped' },
  { id: '45405', name: 'Roof Piece 16 x 4 x 5', category: 'Bricks Sloped' },
  { id: '30614', name: 'Roof Piece 6 x 6 x 3 Peaked', category: 'Bricks Sloped' },
  { id: '5654', name: 'Slope 1 x 4 with 1 x 2 Cutout', category: 'Bricks Sloped' },
  { id: '4569', name: 'Slope 1 x 6 x 1 with 1 x 2 x 1/3 Cutout', category: 'Bricks Sloped' },
  { id: '4515', name: 'Slope 10° 6 x 8', category: 'Bricks Sloped' },
  { id: '5404', name: 'Slope 18° 2 x 1 x 2/3', category: 'Bricks Sloped' },
  { id: '61409', name: 'Slope 18° 2 x 1 x 2/3 with 4 Slots / Grate', category: 'Bricks Sloped' },
  { id: '60477', name: 'Slope 18° 4 x 1', category: 'Bricks Sloped' },
  { id: '30363', name: 'Slope 18° 4 x 2', category: 'Bricks Sloped' },
  {
    id: '30603',
    name: 'Slope 2 x 2 No Studs, with 3 Side Pistons Raised Edges',
    category: 'Bricks Sloped',
  },
  { id: '49618', name: 'Slope 25° 1 x 8 x 3', category: 'Bricks Sloped' },
  { id: '30585a', name: 'Aero Tube Joiner 2 x 4 x 3', category: 'Bricks Special' },
  { id: '30585b', name: 'Aero Tube Joiner 3 x 4 x 3', category: 'Bricks Special' },
  { id: '47993', name: 'Boat Deck Brick 8 x 3 x 4 Railing', category: 'Bricks Special' },
  {
    id: '73562',
    name: 'Bracket 3 x 2 x 1 1/3 with Bottom Stud Holder',
    category: 'Bricks Special',
  },
  { id: '18671', name: 'Bracket 3 x 2 x 1 1/3 with Pin Bottom', category: 'Bricks Special' },
  { id: '5712', name: 'Bracket 5 x 1 x 1 1/3', category: 'Bricks Special' },
  {
    id: '79180',
    name: 'Bracket 5 x 2 x 1 1/3 with Bottom Stud Holder',
    category: 'Bricks Special',
  },
  { id: '11215', name: 'Bracket 5 x 2 x 1 1/3 with Holes, Pin Bottom', category: 'Bricks Special' },
  {
    id: '76766',
    name: 'Bracket 5 x 2 x 2 1/3 with Holes, Inside Stud Holder',
    category: 'Bricks Special',
  },
  {
    id: '6087',
    name: 'Bracket 5 x 2 x 2 1/3 with Holes, Smooth Bottom',
    category: 'Bricks Special',
  },
  { id: '4732', name: 'Bracket 8 x 2 x 1 1/3', category: 'Bricks Special' },
  { id: '60189', name: 'Braille Brick 2 x 4 with 1 Stud ⠁', category: 'Bricks Special' },
  { id: '65552', name: 'Braille Brick 2 x 4 with 1 Stud ⠂', category: 'Bricks Special' },
  { id: '65551', name: 'Braille Brick 2 x 4 with 1 Stud ⠄', category: 'Bricks Special' },
  { id: '65559', name: 'Braille Brick 2 x 4 with 1 Stud ⠐', category: 'Bricks Special' },
  { id: '65557', name: 'Braille Brick 2 x 4 with 1 Studs ⠠', category: 'Bricks Special' },
  { id: '60190', name: 'Braille Brick 2 x 4 with 2 Studs ⠃', category: 'Bricks Special' },
  { id: '60225', name: 'Braille Brick 2 x 4 with 2 Studs ⠅', category: 'Bricks Special' },
  { id: '60191', name: 'Braille Brick 2 x 4 with 2 Studs ⠉', category: 'Bricks Special' },
  { id: '60223', name: 'Braille Brick 2 x 4 with 2 Studs ⠊', category: 'Bricks Special' },
  { id: '36841', name: 'Bracket 1 x 1 - 1 x 1', category: 'Plates Special' },
  { id: '36840', name: 'Bracket 1 x 1 - 1 x 1 Inverted', category: 'Plates Special' },
  { id: '79389', name: 'Bracket 1 x 1 - 1 x 2', category: 'Plates Special' },
  { id: '73825', name: 'Bracket 1 x 1 - 1 x 2 Inverted', category: 'Plates Special' },
  { id: '99781', name: 'Bracket 1 x 2 - 1 x 2', category: 'Plates Special' },
  { id: '99780', name: 'Bracket 1 x 2 - 1 x 2 Inverted', category: 'Plates Special' },
  {
    id: '28802',
    name: 'Bracket 1 x 2 - 1 x 4 [Rounded Corners at Bottom, Square Corners at Top]',
    category: 'Plates Special',
  },
  { id: '10201', name: 'Bracket 1 x 2 - 1 x 4 [Rounded Corners]', category: 'Plates Special' },
  { id: '2436', name: 'Bracket 1 x 2 - 1 x 4 [Square Corners]', category: 'Plates Special' },
  { id: '44728', name: 'Bracket 1 x 2 - 2 x 2', category: 'Plates Special' },
  { id: '7674', name: 'Bracket 1 x 2 - 2 x 2 Centered', category: 'Plates Special' },
  { id: '99207', name: 'Bracket 1 x 2 - 2 x 2 Inverted', category: 'Plates Special' },
  { id: '93274', name: 'Bracket 1 x 2 - 2 x 4', category: 'Plates Special' },
  { id: '7452', name: 'Bracket 1 x 2 - 2 x 4 Inverted', category: 'Plates Special' },
  { id: '6970', name: 'Bracket 1 x 2 - 2 x 6', category: 'Plates Special' },
  { id: '4585', name: 'Bracket 1 x 2 with 1 x 2 Vertical Studs', category: 'Plates Special' },
  { id: '5090', name: 'Bracket 1 x 6 - 2 x 6 Inverted', category: 'Plates Special' },
  { id: '3956', name: 'Bracket 2 x 2 - 2 x 2', category: 'Plates Special' },
  { id: '41682', name: 'Bracket 2 x 2 with 1 x 2 Vertical Studs', category: 'Plates Special' },
  { id: '69906', name: 'Bracket 2 x 3 - 2 x 2, Curved Sides', category: 'Plates Special' },
  { id: '3005', name: 'Brick 1 x 1', category: 'Bricks' },
  { id: '14716', name: 'Brick 1 x 1 x 3', category: 'Bricks' },
  { id: '2453a', name: 'Brick 1 x 1 x 5 with Blocked Open or Hollow Stud', category: 'Bricks' },
  { id: '2453b', name: 'Brick 1 x 1 x 5 with Solid Stud', category: 'Bricks' },
  { id: '6111', name: 'Brick 1 x 10', category: 'Bricks' },
  { id: '6112', name: 'Brick 1 x 12', category: 'Bricks' },
  { id: '2465', name: 'Brick 1 x 16', category: 'Bricks' },
  { id: '3004', name: 'Brick 1 x 2', category: 'Bricks' },
  { id: '3065a', name: 'Brick 1 x 2 with 2 Slots', category: 'Bricks' },
  { id: '3065', name: 'Brick 1 x 2 without Bottom Tube', category: 'Bricks' },
  {
    id: '3065b',
    name: 'Brick 1 x 2 without Bottom Tube, Slotted (with 1 slot)',
    category: 'Bricks',
  },
  { id: '3245a', name: 'Brick 1 x 2 x 2 with Center Pin [Plain]', category: 'Bricks' },
  { id: '3245b', name: 'Brick 1 x 2 x 2 with Inside Axle Holder', category: 'Bricks' },
  { id: '3245c', name: 'Brick 1 x 2 x 2 with Inside Stud Holder', category: 'Bricks' },
  { id: '772', name: 'Brick 1 x 2 x 2 without Bottom Tube', category: 'Bricks' },
  { id: '22886', name: 'Brick 1 x 2 x 3 with Bottom Stud Holder', category: 'Bricks' },
  {
    id: '2454a',
    name: 'Brick 1 x 2 x 5 with Blocked Open Studs and Bottom Stud Holder with Asymmetric Ridges',
    category: 'Bricks',
  },
  { id: '2454b', name: 'Brick 1 x 2 x 5 with Hollow Studs', category: 'Bricks' },
  { id: '46212', name: 'Brick 1 x 2 x 5 without Side Supports', category: 'Bricks' },
  { id: '3622', name: 'Brick 1 x 3', category: 'Bricks' },
  { id: '3024', name: 'Plate 1 x 1', category: 'Plates' },
  { id: '86996', name: 'Plate 1 x 1 x 2/3 with Open Stud', category: 'Plates' },
  { id: '4477', name: 'Plate 1 x 10', category: 'Plates' },
  { id: '60479', name: 'Plate 1 x 12', category: 'Plates' },
  { id: '3023', name: 'Plate 1 x 2', category: 'Plates' },
  { id: '3023a', name: 'Plate 1 x 2 [Old Style Bottom]', category: 'Plates' },
  { id: '3623', name: 'Plate 1 x 3', category: 'Plates' },
  { id: '3710', name: 'Plate 1 x 4', category: 'Plates' },
  { id: '78329', name: 'Plate 1 x 5', category: 'Plates' },
  { id: '3666', name: 'Plate 1 x 6', category: 'Plates' },
  { id: '3460', name: 'Plate 1 x 8', category: 'Plates' },
  { id: '91405', name: 'Plate 16 x 16', category: 'Plates' },
  { id: '3832', name: 'Plate 2 x 10', category: 'Plates' },
  { id: '2445', name: 'Plate 2 x 12', category: 'Plates' },
  { id: '91988', name: 'Plate 2 x 14', category: 'Plates' },
  { id: '4282', name: 'Plate 2 x 16', category: 'Plates' },
  { id: '3022', name: 'Plate 2 x 2', category: 'Plates' },
  { id: '2420', name: 'Plate 2 x 2 Corner', category: 'Plates' },
  { id: '3021', name: 'Plate 2 x 3', category: 'Plates' },
  { id: '73831', name: 'Plate 2 x 3 with 1 x 1 Cutout', category: 'Plates' },
  { id: '107428', name: 'FLAT TILE 2X3, W/ ANGLE, NO. 146', category: 'Tiles Special' },
  { id: '70942', name: 'Tile 1 x 2 with Ball', category: 'Tiles Special' },
  { id: '5091', name: 'Tile 1 x 2 with Stud Notch Left', category: 'Tiles Special' },
  { id: '5092', name: 'Tile 1 x 2 with Stud Notch Right', category: 'Tiles Special' },
  { id: '74169', name: 'Tile 3 x 4 x 2/3 Mickey Mouse', category: 'Tiles Special' },
  { id: '35787', name: 'Tile 45° Cut 2 x 2 (Triangle)', category: 'Tiles Special' },
  {
    id: '3160',
    name: 'Tile 6 x 6 x 2/3, Angled Textured Surface (Ice)',
    category: 'Tiles Special',
  },
  { id: '77813', name: 'Tile Round 1 x 1 Special with Clip-Bar', category: 'Tiles Special' },
  { id: '20482', name: 'Tile Round 1 x 1 with Hollow Bar', category: 'Tiles Special' },
  { id: '74698', name: 'Tile Round 2 x 2 - Thick Lifting Ring', category: 'Tiles Special' },
  { id: '2376', name: 'Tile Round 2 x 2 - Thin Lifting Ring', category: 'Tiles Special' },
  { id: '15535', name: 'Tile Round 2 x 2 with Hole', category: 'Tiles Special' },
  { id: '2555', name: 'Tile Special 1 x 1 with Clip and Straight Tips', category: 'Tiles Special' },
  {
    id: '15712',
    name: 'Tile Special 1 x 1 with Clip with Rounded Edges',
    category: 'Tiles Special',
  },
  {
    id: '12825',
    name: 'Tile Special 1 x 1 with Clip with Rounded Tips',
    category: 'Tiles Special',
  },
  {
    id: '93794',
    name: 'Tile Special 1 x 1 with Clip with Rounded Tips and Center Cut',
    category: 'Tiles Special',
  },
  {
    id: '72078pat0001',
    name: 'Tile Special 1 x 1 with Molded Opal Trans-Clear Diamond',
    category: 'Tiles Special',
  },
  { id: '35649', name: 'Tile Special 1 x 2 Diamond Plain', category: 'Tiles Special' },
  { id: '2412b', name: 'Tile Special 1 x 2 Grille with Bottom Groove', category: 'Tiles Special' },
  {
    id: '2412a',
    name: 'Tile Special 1 x 2 Grille without Bottom Groove',
    category: 'Tiles Special',
  },
  { id: '66404', name: 'FLAT TILE 1X1, NO. 269', category: 'Tiles' },
  { id: '101651', name: 'FLAT TILE 1X1, NO. 282', category: 'Tiles' },
  { id: '101652', name: 'FLAT TILE 1X1, NO. 283', category: 'Tiles' },
  { id: '101653', name: 'FLAT TILE 1X1, NO. 284', category: 'Tiles' },
  { id: '101654', name: 'FLAT TILE 1X1, NO. 285', category: 'Tiles' },
  { id: '101655', name: 'FLAT TILE 1X1, NO. 286', category: 'Tiles' },
  { id: '101645', name: 'FLAT TILE 1X1, NO. 287', category: 'Tiles' },
  { id: '103033', name: 'FLAT TILE 1X1, NO. 292', category: 'Tiles' },
  { id: '103035', name: 'FLAT TILE 1X1, NO. 294', category: 'Tiles' },
  { id: '78171', name: 'FLAT TILE 2X2, NO. 500', category: 'Tiles' },
  { id: '3070b', name: 'Tile 1 x 1 with Groove', category: 'Tiles' },
  { id: '3070a', name: 'Tile 1 x 1 without Groove', category: 'Tiles' },
  { id: '67211', name: 'Tile 1 x 1, Random DOTS Series 2 Print', category: 'Tiles' },
  { id: '73002', name: 'Tile 1 x 1, Random DOTS Series 3 Print', category: 'Tiles' },
  { id: '3069b', name: 'Tile 1 x 2 with Groove', category: 'Tiles' },
  { id: '3069a', name: 'Tile 1 x 2 without Groove', category: 'Tiles' },
  { id: '63864', name: 'Tile 1 x 3', category: 'Tiles' },
  { id: '2431', name: 'Tile 1 x 4 with Groove', category: 'Tiles' },
  { id: '6636', name: 'Tile 1 x 6 with Groove', category: 'Tiles' },
  { id: '4162', name: 'Tile 1 x 8 with Groove', category: 'Tiles' },
  { id: '5692', name: 'Ball with Ears', category: 'Bricks Round and Cones' },
  {
    id: '7324',
    name: 'Brick Round 1 x 1 D. Tube with 45° Elbow and Axle Holes (Crossholes) at Each End',
    category: 'Bricks Round and Cones',
  },
  {
    id: '71076',
    name: 'Brick Round 1 x 1 diameter Tube with 90 Degree Elbow (2 x 2 x 1)',
    category: 'Bricks Round and Cones',
  },
  {
    id: '25214',
    name: 'Brick Round 1 x 1 diameter Tube with 90 Degree Elbow (2 x 2 x 1) and Axle Holes (Crossholes) at each end',
    category: 'Bricks Round and Cones',
  },
  { id: '3062b', name: 'Brick Round 1 x 1 Open Stud', category: 'Bricks Round and Cones' },
  { id: '3062a', name: 'Brick Round 1 x 1 Solid Stud', category: 'Bricks Round and Cones' },
  {
    id: '3062c',
    name: 'Brick Round 1 x 1 Solid Stud, No Bottom Groove',
    category: 'Bricks Round and Cones',
  },
  { id: '6331', name: 'Brick Round 1 x 1 with 3 Bars', category: 'Bricks Round and Cones' },
  {
    id: '4588',
    name: 'Brick Round 1 x 1 with Fins, Open Stud',
    category: 'Bricks Round and Cones',
  },
  { id: '71075', name: 'Brick Round 1 x 1 x 1 2/3', category: 'Bricks Round and Cones' },
  {
    id: '4770',
    name: 'Brick Round 1 x 1 x 2/3 Light Bulb Cover',
    category: 'Bricks Round and Cones',
  },
  {
    id: '20952',
    name: 'Brick Round 1.5 x 1.5 Dome Top [Plain]',
    category: 'Bricks Round and Cones',
  },
  { id: '92947', name: 'Brick Round 2 x 2 [Grill]', category: 'Bricks Round and Cones' },
  {
    id: '5489',
    name: 'Brick Round 2 x 2 D. Tube with 45° Elbow and Axle Holes (Crossholes) at Each End [LONG]',
    category: 'Bricks Round and Cones',
  },
  {
    id: '65473',
    name: 'Brick Round 2 x 2 D. Tube with 45° Elbow and Axle Holes (Crossholes) at Each End [SHORT]',
    category: 'Bricks Round and Cones',
  },
  {
    id: '15395',
    name: 'Brick Round 2 x 2 Dome Bottom [Open Stud]',
    category: 'Bricks Round and Cones',
  },
  {
    id: '5690',
    name: 'Brick Round 2 x 2 Dome Top with 2 Ears',
    category: 'Bricks Round and Cones',
  },
  {
    id: '30367b',
    name: 'Brick Round 2 x 2 Dome Top, Blocked Open Stud, Bottom Axle Holder',
    category: 'Bricks Round and Cones',
  },
  {
    id: '30367a',
    name: 'Brick Round 2 x 2 Dome Top, Blocked Open Stud, No Bottom Axle Holder',
    category: 'Bricks Round and Cones',
  },
  {
    id: '30367c',
    name: 'Brick Round 2 x 2 Dome Top, Hollow Stud',
    category: 'Bricks Round and Cones',
  },
  { id: '7688', name: 'Disc Oval 4 x 6', category: 'Plates Round Curved and Dishes' },
  {
    id: '50990a',
    name: 'Dish 10 x 10 Inverted (Radar) with Hollow Studs',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '50990b',
    name: 'Dish 10 x 10 Inverted (Radar) with Solid Studs',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '4740', name: 'Dish 2 x 2 Inverted [Radar]', category: 'Plates Round Curved and Dishes' },
  { id: '6919', name: 'Dish 2 x 2 with Angled Bar', category: 'Plates Round Curved and Dishes' },
  {
    id: '71128',
    name: 'Dish 2 x 2 x 2/3 Light Reflector',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '43898', name: 'Dish 3 x 3 Inverted [Radar]', category: 'Plates Round Curved and Dishes' },
  { id: '3960', name: 'Dish 4 x 4 Inverted [Radar]', category: 'Plates Round Curved and Dishes' },
  {
    id: '35394',
    name: 'Dish 4 x 4 Inverted with Open Stud [Radar]',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '65138', name: 'Dish 4 x 4 with 4 Studs', category: 'Plates Round Curved and Dishes' },
  { id: '6942', name: 'Dish 5 x 5', category: 'Plates Round Curved and Dishes' },
  {
    id: '44375a',
    name: 'Dish 6 x 6 Inverted (Radar) with Hollow Studs',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '44375b',
    name: 'Dish 6 x 6 Inverted (Radar) with Solid Studs',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '4285b',
    name: 'Dish 6 x 6 Inverted, Radar / Webbed [Anti-studs at 90°]',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '4285a',
    name: 'Dish 6 x 6 Inverted, Radar / Webbed [No Anti-studs]',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '18859',
    name: 'Dish 8 x 8 Inverted [Radar], Hollow Studs',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '3961',
    name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Rounded Anti-stud Underside',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '3961a',
    name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Squared Anti-stud Underside',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '35154',
    name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Squared Anti-stud Underside, Anti-Studs on Edges',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '98606',
    name: 'Dish 9 x 9 Inverted with Pin Hole (Radar)',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '6108', name: 'Brick Arch 1 x 12 x 3', category: 'Bricks Curved' },
  { id: '14707', name: 'Brick Arch 1 x 12 x 3 Raised Arch', category: 'Bricks Curved' },
  {
    id: '18838',
    name: 'Brick Arch 1 x 12 x 3 Raised Arch with 5 Cross Supports',
    category: 'Bricks Curved',
  },
  { id: '6184', name: 'Brick Arch 1 x 12 x 5 Curved Top', category: 'Bricks Curved' },
  { id: '4490', name: 'Brick Arch 1 x 3', category: 'Bricks Curved' },
  { id: '5843', name: 'Brick Arch 1 x 3 x 1 2/3 Curved Top', category: 'Bricks Curved' },
  { id: '88292', name: 'Brick Arch 1 x 3 x 2', category: 'Bricks Curved' },
  { id: '6005', name: 'Brick Arch 1 x 3 x 2 Curved Top', category: 'Bricks Curved' },
  { id: '18653', name: 'Brick Arch 1 x 3 x 2 Inverted [Inside Bow]', category: 'Bricks Curved' },
  { id: '5850', name: 'Brick Arch 1 x 3 x 2, Straight End', category: 'Bricks Curved' },
  { id: '13965', name: 'Brick Arch 1 x 3 x 3 [Gothic]', category: 'Bricks Curved' },
  { id: '3659', name: 'Brick Arch 1 x 4', category: 'Bricks Curved' },
  { id: '6182', name: 'Brick Arch 1 x 4 x 2', category: 'Bricks Curved' },
  { id: '5844', name: 'Brick Arch 1 x 4 x 2 1/3 Curved Top', category: 'Bricks Curved' },
  { id: '80543', name: 'Brick Arch 1 x 4 x 3', category: 'Bricks Curved' },
  { id: '3572', name: 'Brick Arch 1 x 5 x 2', category: 'Bricks Curved' },
  { id: '5845', name: 'Brick Arch 1 x 5 x 3 1/3 Curved Top', category: 'Bricks Curved' },
  {
    id: '14395',
    name: 'Brick Arch 1 x 5 x 4 [Continuous Bow, Raised Underside Cross Supports]',
    category: 'Bricks Curved',
  },
  { id: '2339', name: 'Brick Arch 1 x 5 x 4 [Continuous Bow]', category: 'Bricks Curved' },
  {
    id: '76768',
    name: 'Brick Arch 1 x 5 x 4 [Irregular Bow, Raised Underside Cross Supports]',
    category: 'Bricks Curved',
  },
  {
    id: '79846',
    name: 'Plate Angled 2 x 2 with Step and Hole in Center',
    category: 'Plates Angled',
  },
  { id: '44666', name: 'Plate Angles Hexagonal 14 X 18', category: 'Plates Angled' },
  {
    id: '92584',
    name: 'Wedge Plate 10 x 10 Cut Corner [No Centre Studs]',
    category: 'Plates Angled',
  },
  {
    id: '2401',
    name: 'Wedge Plate 10 x 10 with 4x4 Cutout and Cut Corner',
    category: 'Plates Angled',
  },
  { id: '47397', name: 'Wedge Plate 12 x 3 Left', category: 'Plates Angled' },
  { id: '47398', name: 'Wedge Plate 12 x 3 Right', category: 'Plates Angled' },
  { id: '26601', name: 'Wedge Plate 2 x 2 Cut Corner', category: 'Plates Angled' },
  { id: '24299', name: 'Wedge Plate 2 x 2 Left', category: 'Plates Angled' },
  { id: '24307', name: 'Wedge Plate 2 x 2 Right', category: 'Plates Angled' },
  { id: '51739', name: 'Wedge Plate 2 x 4', category: 'Plates Angled' },
  { id: '65429', name: 'Wedge Plate 2 x 4 27° Left', category: 'Plates Angled' },
  { id: '65426', name: 'Wedge Plate 2 x 4 27° Right', category: 'Plates Angled' },
  { id: '43723', name: 'Wedge Plate 3 x 2 Left', category: 'Plates Angled' },
  { id: '43722', name: 'Wedge Plate 3 x 2 Right', category: 'Plates Angled' },
  { id: '2450', name: 'Wedge Plate 3 x 3 Cut Corner', category: 'Plates Angled' },
  { id: '48183', name: 'Wedge Plate 3 x 4 with Stud Notches', category: 'Plates Angled' },
  {
    id: '90194',
    name: 'Wedge Plate 3 x 4 with Stud Notches [Reinforced Underside]',
    category: 'Plates Angled',
  },
  { id: '4859', name: 'Wedge Plate 3 x 4 without Stud Notches', category: 'Plates Angled' },
  { id: '2419', name: 'Wedge Plate 3 x 6 Cut Corners', category: 'Plates Angled' },
  { id: '15706', name: 'Wedge Plate 4 Stud 45° Angle Plate', category: 'Plates Angled' },
  { id: '83079', name: 'FLAT TILE 1X1, ROUND, NO. 184', category: 'Tiles Round and Curved' },
  { id: '83085', name: 'FLAT TILE 1X1, ROUND, NO. 208', category: 'Tiles Round and Curved' },
  { id: '39739', name: 'Tile 1 x 1 Heart', category: 'Tiles Round and Curved' },
  { id: '27925', name: 'Tile 2 x 2 Curved, Macaroni', category: 'Tiles Round and Curved' },
  {
    id: '7836',
    name: 'Tile 2 x 2 Curved, Macaroni, Center Anti-Stud',
    category: 'Tiles Round and Curved',
  },
  { id: '79393', name: 'Tile 3 x 3 Curved, Macaroni', category: 'Tiles Round and Curved' },
  { id: '27507', name: 'Tile 4 x 4 Curved, Macaroni', category: 'Tiles Round and Curved' },
  { id: '65474', name: 'Tile 6 x 8 with Rounded Corners', category: 'Tiles Round and Curved' },
  {
    id: '73099',
    name: 'Tile Pack 1 x 1 Half Circle, Random DOTS Series 4 Print',
    category: 'Tiles Round and Curved',
  },
  { id: '77486', name: 'Tile Pack 169 - Letters', category: 'Tiles Round and Curved' },
  { id: '83152', name: 'Tile Pack for 41949-1', category: 'Tiles Round and Curved' },
  { id: '66402', name: 'Tile Pack for 41957-1', category: 'Tiles Round and Curved' },
  { id: '98138', name: 'Tile Round 1 x 1', category: 'Tiles Round and Curved' },
  { id: '24246', name: 'Tile Round 1 x 1 Half Circle', category: 'Tiles Round and Curved' },
  { id: '25269', name: 'Tile Round 1 x 1 Quarter', category: 'Tiles Round and Curved' },
  {
    id: '67222',
    name: 'Tile Round 1 x 1 Random DOTS Series 1 Print',
    category: 'Tiles Round and Curved',
  },
  {
    id: '72046pat0001',
    name: 'Tile Round 1 x 1 with Molded Trans-Bright Pink Star',
    category: 'Tiles Round and Curved',
  },
  {
    id: '72046pat0002',
    name: 'Tile Round 1 x 1 with Molded Trans-Dark Blue Star',
    category: 'Tiles Round and Curved',
  },
  {
    id: '67216',
    name: 'Tile Round 1 x 1, Random DOTS Mega Pack 1 Print',
    category: 'Tiles Round and Curved',
  },
  {
    id: '67217',
    name: 'Tile Round 1 x 1, Random DOTS Mega Pack 2 Print',
    category: 'Tiles Round and Curved',
  },
];
