// Auto-generated from Rebrickable database
// Filtered to only include parts with LDraw .dat files
// Sorted by part number (lower = older = more common)
// Generated: 2026-04-07T21:55:29.869Z

export const RebrickableCategories = [
  'Baseplates',
  'Bricks Sloped',
  'Bricks Special',
  'Plates Special',
  'Bricks',
  'Plates',
  'Tiles Special',
  'Tiles',
  'Bricks Round and Cones',
  'Plates Round Curved and Dishes',
  'Bricks Curved',
  'Plates Angled',
  'Tiles Round and Curved',
];

export const RebrickableParts = {
  Baseplates: [
    {
      id: '10a',
      name: 'Baseplate 24 x 32 with Rounded Corners',
      category: 'Baseplates',
    },
    {
      id: '10b',
      name: 'Baseplate 24 x 32 with Squared Corners',
      category: 'Baseplates',
    },
    {
      id: '184',
      name: 'Baseplate 16 x 18',
      category: 'Baseplates',
    },
    {
      id: '210',
      name: 'Baseplate 16 x 22',
      category: 'Baseplates',
    },
    {
      id: '309',
      name: 'Baseplate 32 x 32 Split with 2 x 14 Center Studs [Plain]',
      category: 'Baseplates',
    },
    {
      id: '367',
      name: 'Baseplate 24 x 24 with Studs on Edges',
      category: 'Baseplates',
    },
    {
      id: '374',
      name: 'Baseplate 16 x 32 with Rounded Corners [Plain]',
      category: 'Baseplates',
    },
    {
      id: '397',
      name: 'Baseplate 10 x 16',
      category: 'Baseplates',
    },
    {
      id: '455',
      name: 'Baseplate 16 x 24 with Rounded Corners',
      category: 'Baseplates',
    },
    {
      id: '606',
      name: 'Baseplate 32 x 32 with 9-Stud Straight [Plain]',
      category: 'Baseplates',
    },
    {
      id: '607',
      name: 'Baseplate 32 x 32 with 9-Stud Crossroads [Plain]',
      category: 'Baseplates',
    },
    {
      id: '608',
      name: 'Baseplate 32 x 32 with 9-Stud T Intersection [Plain]',
      category: 'Baseplates',
    },
    {
      id: '609',
      name: 'Baseplate 32 x 32 with 9-Stud Curve [Plain]',
      category: 'Baseplates',
    },
    {
      id: '648',
      name: 'Baseplate 16 x 32 with Railway Station Stud Print [342]',
      category: 'Baseplates',
    },
    {
      id: '700',
      name: 'Thin Baseplate 10 x 20 x 0.5',
      category: 'Baseplates',
    },
    {
      id: '785',
      name: 'Baseplate 24 x 32 with Studs on Edges',
      category: 'Baseplates',
    },
    {
      id: '809',
      name: 'Baseplate 24 x 40 Gravel Quarry with Sets 360 / 580 Dots Print',
      category: 'Baseplates',
    },
    {
      id: '811',
      name: 'Baseplate 16 x 32 with Warehouse Stud Print [341]',
      category: 'Baseplates',
    },
    {
      id: '820',
      name: 'Baseplate Raised 8 x 18 with Garage Floor Plate (Old style)',
      category: 'Baseplates',
    },
    {
      id: '896',
      name: 'Baseplate 14 x 20 with Rounded Corners [Plain]',
      category: 'Baseplates',
    },
    {
      id: '0901',
      name: 'Baseplate 16 x 30 with Set 080 Yellow House Print',
      category: 'Baseplates',
    },
    {
      id: '0902',
      name: 'Baseplate 16 x 24 with Set 080 Small White House Print',
      category: 'Baseplates',
    },
    {
      id: '0903',
      name: 'Baseplate 16 x 24 with Set 080 Red House Print',
      category: 'Baseplates',
    },
    {
      id: '0904',
      name: 'Baseplate 16 x 24 with Set 080 Large White House Print',
      category: 'Baseplates',
    },
    {
      id: '911',
      name: 'Baseplate 10 x 48 Train Ferry, Reduced Studs at Center [343-1]',
      category: 'Baseplates',
    },
    {
      id: '912',
      name: 'Baseplate 16 x 16 Control Tower Set 340',
      category: 'Baseplates',
    },
    {
      id: '2552',
      name: 'Baseplate Raised 32 x 32 with Ramp and Pit [Plain]',
      category: 'Baseplates',
    },
    {
      id: '2617',
      name: 'Baseplate Raised 16 x 16 x 2 1/3 Platform',
      category: 'Baseplates',
    },
    {
      id: '2642',
      name: 'Baseplate Raised 16 x 16 x 2 1/3 Ramp',
      category: 'Baseplates',
    },
    {
      id: '3334',
      name: 'Baseplate 16 x 24',
      category: 'Baseplates',
    },
  ],
  'Bricks Sloped': [
    {
      id: '678',
      name: 'Homemaker Awning 2 x 6',
      category: 'Bricks Sloped',
    },
    {
      id: '962',
      name: 'Slope 45° 2 x 2 Double Convex / Double Concave',
      category: 'Bricks Sloped',
    },
    {
      id: '1762',
      name: 'Slope 33° 2 x 2 Double / Inverted',
      category: 'Bricks Sloped',
    },
    {
      id: '2310',
      name: 'Slope 45° 2 x 1 Inverted with 2/3 Cutout',
      category: 'Bricks Sloped',
    },
    {
      id: '2341',
      name: 'Slope Inverted 45° 3 x 1 Double with 2 Completely Open Studs',
      category: 'Bricks Sloped',
    },
    {
      id: '2449',
      name: 'Slope Inverted 75° 2 x 1 x 3',
      category: 'Bricks Sloped',
    },
    {
      id: '2875',
      name: 'Slope 45° 2 x 6 x 2/3',
      category: 'Bricks Sloped',
    },
    {
      id: '2937',
      name: 'Slope 55° 1 x 6 x 5 with Bottom Stud Holders',
      category: 'Bricks Sloped',
    },
    {
      id: '3037',
      name: 'Slope 45° 2 x 4',
      category: 'Bricks Sloped',
    },
    {
      id: '3038',
      name: 'Slope 45° 2 x 3',
      category: 'Bricks Sloped',
    },
    {
      id: '3039',
      name: 'Slope 45° 2 x 2',
      category: 'Bricks Sloped',
    },
    {
      id: '3040b',
      name: 'Slope 45° 2 x 1 with Bottom Pin',
      category: 'Bricks Sloped',
    },
    {
      id: '3040a',
      name: 'Slope 45° 2 x 1 without Bottom Pin',
      category: 'Bricks Sloped',
    },
    {
      id: '3041',
      name: 'Slope 45° 2 x 4 Double',
      category: 'Bricks Sloped',
    },
    {
      id: '3042',
      name: 'Slope 45° 2 x 3 Double',
      category: 'Bricks Sloped',
    },
    {
      id: '3043',
      name: 'Slope 45° 2 x 2 Double',
      category: 'Bricks Sloped',
    },
    {
      id: '3044c',
      name: 'Slope 45° 2 x 1 Double with Inside Stud Holder',
      category: 'Bricks Sloped',
    },
    {
      id: '3044b',
      name: 'Slope 45° 2 x 1 Double with Ovoid Bottom Pin',
      category: 'Bricks Sloped',
    },
    {
      id: '3044a',
      name: 'Slope 45° 2 x 1 Double without Bottom Pin',
      category: 'Bricks Sloped',
    },
    {
      id: '3045',
      name: 'Slope 45° 2 x 2 Double Convex',
      category: 'Bricks Sloped',
    },
    {
      id: '3048b',
      name: 'Slope 45° 2 x 1 Triple Smooth',
      category: 'Bricks Sloped',
    },
    {
      id: '3048a',
      name: 'Slope 45° 2 x 1 Triple with Hollow Underside',
      category: 'Bricks Sloped',
    },
    {
      id: '3049d',
      name: 'Slope 45° 2 x 1 Double / Inverted with Bottom Stud Holder',
      category: 'Bricks Sloped',
    },
    {
      id: '3049a',
      name: 'Slope 45° 2 x 1 Double / Inverted with Bottom Tube',
      category: 'Bricks Sloped',
    },
    {
      id: '3049c',
      name: 'Slope 45° 2 x 1 Double / Inverted with Hollow Bottom',
      category: 'Bricks Sloped',
    },
    {
      id: '3297',
      name: 'Slope 33° 3 x 4',
      category: 'Bricks Sloped',
    },
    {
      id: '3298',
      name: 'Slope 33° 3 x 2',
      category: 'Bricks Sloped',
    },
    {
      id: '3299',
      name: 'Slope 33° 2 x 4 Double',
      category: 'Bricks Sloped',
    },
    {
      id: '3300',
      name: 'Slope 33° 2 x 2 Double',
      category: 'Bricks Sloped',
    },
    {
      id: '3660',
      name: 'Slope Inverted 45° 2 x 2 [Ovoid Bottom Pin, Bar-sized Stud Holes]',
      category: 'Bricks Sloped',
    },
  ],
  'Bricks Special': [
    {
      id: '2336',
      name: 'Brick Special, Cockpit Space Nose',
      category: 'Bricks Special',
    },
    {
      id: '2434',
      name: 'Brick Special 2 x 4 x 2 with Studs on Sides',
      category: 'Bricks Special',
    },
    {
      id: '2458',
      name: 'Brick Special 1 x 2 with Pin',
      category: 'Bricks Special',
    },
    {
      id: '2653',
      name: 'Brick Special 1 x 4 with Groove',
      category: 'Bricks Special',
    },
    {
      id: '2832',
      name: 'Brick Special 2 x 8 x 5/6 with No Top Studs, and Channel on Ends, and Stud Holes on Sides',
      category: 'Bricks Special',
    },
    {
      id: '2833',
      name: 'Brick Special 1 x 8 x 5/6 with No Top Studs and Channel on Ends',
      category: 'Bricks Special',
    },
    {
      id: '2877',
      name: 'Brick Special 1 x 2 with Grille',
      category: 'Bricks Special',
    },
    {
      id: '2921',
      name: 'Brick Special 1 x 1 with Handle',
      category: 'Bricks Special',
    },
    {
      id: '3134',
      name: 'Brick Special 1 x 2 with Cable Holding Square Cutout',
      category: 'Bricks Special',
    },
    {
      id: '3487',
      name: 'Brick Special 8 x 10 x 2 with 6 x 10 Recessed, Pin Holes',
      category: 'Bricks Special',
    },
    {
      id: '3581',
      name: 'Brick Special 1 x 1 x 2 with Shutter Holder',
      category: 'Bricks Special',
    },
    {
      id: '3668',
      name: 'Brick Special 2 x 6 x 1 1/3 with Axle Holes and 2 x 4 Recessed, Ridges at Underside',
      category: 'Bricks Special',
    },
    {
      id: '4070',
      name: 'Brick Special 1 x 1 with Headlight',
      category: 'Bricks Special',
    },
    {
      id: '4216',
      name: 'Brick Special 1 x 2 with Groove',
      category: 'Bricks Special',
    },
    {
      id: '4217',
      name: 'Brick Special 1 x 14 Grooved',
      category: 'Bricks Special',
    },
    {
      id: '4595',
      name: 'Brick Special 1 x 2 x 2/3 with Studs on Sides',
      category: 'Bricks Special',
    },
    {
      id: '4729',
      name: 'Brick Special 2 x 2 No Studs, Top Pin',
      category: 'Bricks Special',
    },
    {
      id: '4730',
      name: 'Brick Special 2 x 2 with Pin and No Axle Hole',
      category: 'Bricks Special',
    },
    {
      id: '4732',
      name: 'Bracket 8 x 2 x 1 1/3',
      category: 'Bricks Special',
    },
    {
      id: '4733',
      name: 'Brick Special 1 x 1 Studs on 4 Sides',
      category: 'Bricks Special',
    },
    {
      id: '4747',
      name: 'Brick Special 2 x 4 with Coupling, Male',
      category: 'Bricks Special',
    },
    {
      id: '4748',
      name: 'Brick Special 2 x 4 with Coupling, Female',
      category: 'Bricks Special',
    },
    {
      id: '4920',
      name: 'Brick Special 1 x 2 with Rotation Joint Pin',
      category: 'Bricks Special',
    },
    {
      id: '5712',
      name: 'Bracket 5 x 1 x 1 1/3',
      category: 'Bricks Special',
    },
    {
      id: '6032',
      name: 'Brick Special Octagonal 2 x 3 x 1 2/3 Sloped',
      category: 'Bricks Special',
    },
    {
      id: '6037',
      name: 'Brick Special Octagonal 2 x 2 x 3 1/3',
      category: 'Bricks Special',
    },
    {
      id: '6042',
      name: 'Brick Special Octagonal 2 x 2 x 3 1/3 with Side Studs',
      category: 'Bricks Special',
    },
    {
      id: '6043',
      name: 'Brick Special Octagonal 2 x 2 x 3 1/3 Corner',
      category: 'Bricks Special',
    },
    {
      id: '6056',
      name: 'Brick Special 2 x 2 x 6 with Groove',
      category: 'Bricks Special',
    },
    {
      id: '6061',
      name: 'Brick 2 x 4 x 2 with Holes on Sides',
      category: 'Bricks Special',
    },
  ],
  'Plates Special': [
    {
      id: '422',
      name: 'Plate Special 2 x 2 with Small Holes for Metal Axle',
      category: 'Plates Special',
    },
    {
      id: '709',
      name: 'Plate Special 4 x 6 with Hole',
      category: 'Plates Special',
    },
    {
      id: '711',
      name: 'Plate Special 5 x 6 with Hole',
      category: 'Plates Special',
    },
    {
      id: '737',
      name: 'Plate Special 2 x 4 with Train Coupler Closed for Hook',
      category: 'Plates Special',
    },
    {
      id: '753',
      name: 'Plate Special 2 x 4 with Train Coupler, Open for Magnet [Reinforced]',
      category: 'Plates Special',
    },
    {
      id: '967',
      name: 'Plate Special 4 x 8 with Helicopter Rotor Holder',
      category: 'Plates Special',
    },
    {
      id: '1745',
      name: 'Plate Round 1 x 2 Half Circle with Stud (Jumper)',
      category: 'Plates Special',
    },
    {
      id: '1942',
      name: 'Plate Special 2 x 4 Fresnel Lens',
      category: 'Plates Special',
    },
    {
      id: '2436',
      name: 'Bracket 1 x 2 - 1 x 4 [Square Corners]',
      category: 'Plates Special',
    },
    {
      id: '2444',
      name: 'Plate Special 2 x 2 with 1 Pin Hole [Split Underside Ribs]',
      category: 'Plates Special',
    },
    {
      id: '2476a',
      name: 'Plate Special 2 x 2 with Pin on Bottom',
      category: 'Plates Special',
    },
    {
      id: '2476b',
      name: 'Plate Special 2 x 2 with Pin on Bottom, Small Holes in Plate and Rotational Locking Fingers on Underside',
      category: 'Plates Special',
    },
    {
      id: '2508',
      name: 'Plate Special 1 x 2 with Long Towball',
      category: 'Plates Special',
    },
    {
      id: '2539',
      name: 'Plate Special 6 x 6 Octagonal with Square Hole and 4 Clips (Boat Mast Platform)',
      category: 'Plates Special',
    },
    {
      id: '2540',
      name: 'Plate Special 1 x 2 Side Handle [Free Ends]',
      category: 'Plates Special',
    },
    {
      id: '2612',
      name: 'Plate Special 16 x 16 x 2/3 with 7 Recessed Edges, 8 x 8 Cutout',
      category: 'Plates Special',
    },
    {
      id: '2628',
      name: 'Plate Special 8 x 8 x 2/3 with Four 1 x 4 Recessed Edges',
      category: 'Plates Special',
    },
    {
      id: '2629',
      name: 'Plate Special 8 x 16 x 2/3 with Six Recessed Edges',
      category: 'Plates Special',
    },
    {
      id: '2817',
      name: 'Plate Special 2 x 2 with 2 Pin Holes',
      category: 'Plates Special',
    },
    {
      id: '2926',
      name: 'Plate Special 1 x 4 with Wheels Holder',
      category: 'Plates Special',
    },
    {
      id: '3058a',
      name: 'Plate Special 6 x 16 with Motor Opening Narrow',
      category: 'Plates Special',
    },
    {
      id: '3058b',
      name: 'Plate Special 6 x 16 with Motor Opening Wide',
      category: 'Plates Special',
    },
    {
      id: '3170',
      name: 'Plate Special 1 x 2 with 2 End Towballs',
      category: 'Plates Special',
    },
    {
      id: '3172',
      name: 'Plate Special 1 x 2 with Pin Hole On Side',
      category: 'Plates Special',
    },
    {
      id: '3176',
      name: 'Plate Special 3 x 2 with Rounded End, Hole',
      category: 'Plates Special',
    },
    {
      id: '3183a',
      name: 'Plate Special 1 x 4 with Towball Socket, Long, 2 Slots',
      category: 'Plates Special',
    },
    {
      id: '3183b',
      name: 'Plate Special 1 x 4 with Towball Socket, Long, 4 Slots',
      category: 'Plates Special',
    },
    {
      id: '3183c',
      name: 'Plate Special 1 x 4 with Towball Socket, Short, 4 Slots',
      category: 'Plates Special',
    },
    {
      id: '3184',
      name: 'Plate Special 1 x 4 with Towball',
      category: 'Plates Special',
    },
    {
      id: '3386',
      name: 'Plate 1 x 1 x 2/3 Half Round with Side Stud',
      category: 'Plates Special',
    },
  ],
  Bricks: [
    {
      id: '700b',
      name: "Brick 10 x 20 without Bottom Tubes, with '+' Cross Support (early Baseplate)",
      category: 'Bricks',
    },
    {
      id: '700a',
      name: "Brick 10 x 20 without Bottom Tubes, with '+' Cross Support and 4 Side Supports (early Baseplate)",
      category: 'Bricks',
    },
    {
      id: '702',
      name: 'Brick 4 x 4 Corner',
      category: 'Bricks',
    },
    {
      id: '733',
      name: 'Brick 10 x 10 without Bottom Tubes, without Cross Supports',
      category: 'Bricks',
    },
    {
      id: '772',
      name: 'Brick 1 x 2 x 2 without Bottom Tube',
      category: 'Bricks',
    },
    {
      id: '2356',
      name: 'Brick 4 x 6',
      category: 'Bricks',
    },
    {
      id: '2357',
      name: 'Brick 2 x 2 Corner',
      category: 'Bricks',
    },
    {
      id: '2453a',
      name: 'Brick 1 x 1 x 5 with Blocked Open or Hollow Stud',
      category: 'Bricks',
    },
    {
      id: '2453b',
      name: 'Brick 1 x 1 x 5 with Solid Stud',
      category: 'Bricks',
    },
    {
      id: '2454a',
      name: 'Brick 1 x 2 x 5 with Blocked Open Studs and Bottom Stud Holder with Asymmetric Ridges',
      category: 'Bricks',
    },
    {
      id: '2454b',
      name: 'Brick 1 x 2 x 5 with Hollow Studs',
      category: 'Bricks',
    },
    {
      id: '2456',
      name: 'Brick 2 x 6',
      category: 'Bricks',
    },
    {
      id: '2465',
      name: 'Brick 1 x 16',
      category: 'Bricks',
    },
    {
      id: '3001',
      name: 'Brick 2 x 4',
      category: 'Bricks',
    },
    {
      id: '3001b',
      name: 'Brick 2 x 4 without Cross Supports, with Hole in Top',
      category: 'Bricks',
    },
    {
      id: '3002',
      name: 'Brick 2 x 3',
      category: 'Bricks',
    },
    {
      id: '3003',
      name: 'Brick 2 x 2',
      category: 'Bricks',
    },
    {
      id: '3004',
      name: 'Brick 1 x 2',
      category: 'Bricks',
    },
    {
      id: '3005',
      name: 'Brick 1 x 1',
      category: 'Bricks',
    },
    {
      id: '3006',
      name: 'Brick 2 x 10',
      category: 'Bricks',
    },
    {
      id: '3007',
      name: 'Brick 2 x 8',
      category: 'Bricks',
    },
    {
      id: '3008',
      name: 'Brick 1 x 8',
      category: 'Bricks',
    },
    {
      id: '3009',
      name: 'Brick 1 x 6',
      category: 'Bricks',
    },
    {
      id: '3010',
      name: 'Brick 1 x 4',
      category: 'Bricks',
    },
    {
      id: '3065',
      name: 'Brick 1 x 2 without Bottom Tube',
      category: 'Bricks',
    },
    {
      id: '3066',
      name: 'Brick 1 x 4 without Bottom Tubes',
      category: 'Bricks',
    },
    {
      id: '3067',
      name: 'Brick 1 x 6 with No Bottom Tubes',
      category: 'Bricks',
    },
    {
      id: '3245a',
      name: 'Brick 1 x 2 x 2 with Center Pin [Plain]',
      category: 'Bricks',
    },
    {
      id: '3245b',
      name: 'Brick 1 x 2 x 2 with Inside Axle Holder',
      category: 'Bricks',
    },
    {
      id: '3245c',
      name: 'Brick 1 x 2 x 2 with Inside Stud Holder',
      category: 'Bricks',
    },
  ],
  Plates: [
    {
      id: '728',
      name: 'Plate 8 x 11',
      category: 'Plates',
    },
    {
      id: '2420',
      name: 'Plate 2 x 2 Corner',
      category: 'Plates',
    },
    {
      id: '2445',
      name: 'Plate 2 x 12',
      category: 'Plates',
    },
    {
      id: '2639',
      name: 'Plate 4 x 4 Corner',
      category: 'Plates',
    },
    {
      id: '3020',
      name: 'Plate 2 x 4',
      category: 'Plates',
    },
    {
      id: '3021',
      name: 'Plate 2 x 3',
      category: 'Plates',
    },
    {
      id: '3022',
      name: 'Plate 2 x 2',
      category: 'Plates',
    },
    {
      id: '3023',
      name: 'Plate 1 x 2',
      category: 'Plates',
    },
    {
      id: '3023a',
      name: 'Plate 1 x 2 [Old Style Bottom]',
      category: 'Plates',
    },
    {
      id: '3024',
      name: 'Plate 1 x 1',
      category: 'Plates',
    },
    {
      id: '3026',
      name: 'Plate 6 x 24',
      category: 'Plates',
    },
    {
      id: '3027',
      name: 'Plate 6 x 16',
      category: 'Plates',
    },
    {
      id: '3028',
      name: 'Plate 6 x 12',
      category: 'Plates',
    },
    {
      id: '3029',
      name: 'Plate 4 x 12',
      category: 'Plates',
    },
    {
      id: '3030',
      name: 'Plate 4 x 10',
      category: 'Plates',
    },
    {
      id: '3031',
      name: 'Plate 4 x 4',
      category: 'Plates',
    },
    {
      id: '3032',
      name: 'Plate 4 x 6',
      category: 'Plates',
    },
    {
      id: '3033',
      name: 'Plate 6 x 10',
      category: 'Plates',
    },
    {
      id: '3034',
      name: 'Plate 2 x 8',
      category: 'Plates',
    },
    {
      id: '3035',
      name: 'Plate 4 x 8',
      category: 'Plates',
    },
    {
      id: '3036',
      name: 'Plate 6 x 8',
      category: 'Plates',
    },
    {
      id: '3456',
      name: 'Plate 6 x 14',
      category: 'Plates',
    },
    {
      id: '3460',
      name: 'Plate 1 x 8',
      category: 'Plates',
    },
    {
      id: '3623',
      name: 'Plate 1 x 3',
      category: 'Plates',
    },
    {
      id: '3666',
      name: 'Plate 1 x 6',
      category: 'Plates',
    },
    {
      id: '3710',
      name: 'Plate 1 x 4',
      category: 'Plates',
    },
    {
      id: '3795',
      name: 'Plate 2 x 6',
      category: 'Plates',
    },
    {
      id: '3832',
      name: 'Plate 2 x 10',
      category: 'Plates',
    },
    {
      id: '3958',
      name: 'Plate 6 x 6',
      category: 'Plates',
    },
    {
      id: '4282',
      name: 'Plate 2 x 16',
      category: 'Plates',
    },
  ],
  'Tiles Special': [
    {
      id: '2376',
      name: 'Tile Round 2 x 2 - Thin Lifting Ring',
      category: 'Tiles Special',
    },
    {
      id: '2412b',
      name: 'Tile Special 1 x 2 Grille with Bottom Groove',
      category: 'Tiles Special',
    },
    {
      id: '2412a',
      name: 'Tile Special 1 x 2 Grille without Bottom Groove',
      category: 'Tiles Special',
    },
    {
      id: '2432',
      name: 'Tile Special 1 x 2 with Handle',
      category: 'Tiles Special',
    },
    {
      id: '2460',
      name: 'Tile Special 2 x 2 with Top Pin',
      category: 'Tiles Special',
    },
    {
      id: '2555',
      name: 'Tile Special 1 x 1 with Clip and Straight Tips',
      category: 'Tiles Special',
    },
    {
      id: '3160',
      name: 'Tile 6 x 6 x 2/3, Angled Textured Surface (Ice)',
      category: 'Tiles Special',
    },
    {
      id: '3395',
      name: 'Tile Special 2 x 4 Inverted',
      category: 'Tiles Special',
    },
    {
      id: '3396',
      name: 'Tile Special 2 x 2 with 2 Quarter Round Cutouts',
      category: 'Tiles Special',
    },
    {
      id: '3567',
      name: 'Tile Special Round 2 x 2 Inverted',
      category: 'Tiles Special',
    },
    {
      id: '4092',
      name: 'Tile Special 6 x 4 with Beveled Edges and 7mm Pin (Train Bogie Plate)',
      category: 'Tiles Special',
    },
    {
      id: '5091',
      name: 'Tile 1 x 2 with Stud Notch Left',
      category: 'Tiles Special',
    },
    {
      id: '5092',
      name: 'Tile 1 x 2 with Stud Notch Right',
      category: 'Tiles Special',
    },
    {
      id: '6805',
      name: 'Tile Special 2 x 2 with Ring',
      category: 'Tiles Special',
    },
    {
      id: '7828',
      name: 'Wedge Tile 2 x 2 Left',
      category: 'Tiles Special',
    },
    {
      id: '7829',
      name: 'Wedge Tile 2 x 2 Right',
      category: 'Tiles Special',
    },
    {
      id: '11203',
      name: 'Tile Special 2 x 2 Inverted',
      category: 'Tiles Special',
    },
    {
      id: '11609',
      name: 'Tile, Star with Stud Holder, Pin Hole',
      category: 'Tiles Special',
    },
    {
      id: '12825',
      name: 'Tile Special 1 x 1 with Clip with Rounded Tips',
      category: 'Tiles Special',
    },
    {
      id: '15209',
      name: 'Tile Special 1 x 2 with Two Vertical Teeth / Tooth',
      category: 'Tiles Special',
    },
    {
      id: '15535',
      name: 'Tile Round 2 x 2 with Hole',
      category: 'Tiles Special',
    },
    {
      id: '15712',
      name: 'Tile Special 1 x 1 with Clip with Rounded Edges',
      category: 'Tiles Special',
    },
    {
      id: '20482',
      name: 'Tile Round 1 x 1 with Hollow Bar',
      category: 'Tiles Special',
    },
    {
      id: '22385',
      name: 'Tile Special 2 x 3 Pentagonal',
      category: 'Tiles Special',
    },
    {
      id: '24445',
      name: 'Tile Special 1 x 2 with Minifig Neck Pin',
      category: 'Tiles Special',
    },
    {
      id: '27263',
      name: 'Tile Special 2 x 2 Corner with Cut Corner - Facet',
      category: 'Tiles Special',
    },
    {
      id: '30256',
      name: 'Tile Special 2 x 2 with Bar and Stud',
      category: 'Tiles Special',
    },
    {
      id: '30350a',
      name: 'Tile Special 2 x 3 with 2 Clips [Angled Clips]',
      category: 'Tiles Special',
    },
    {
      id: '30350b',
      name: 'Tile Special 2 x 3 with 2 Clips [Thick Open O Clips]',
      category: 'Tiles Special',
    },
    {
      id: '30350c',
      name: 'Tile Special 2 x 3 with 2 Clips [Thick U Clips]',
      category: 'Tiles Special',
    },
  ],
  Tiles: [
    {
      id: '1751',
      name: 'Tile 4 x 4',
      category: 'Tiles',
    },
    {
      id: '2431',
      name: 'Tile 1 x 4 with Groove',
      category: 'Tiles',
    },
    {
      id: '3068b',
      name: 'Tile 2 x 2 with Groove',
      category: 'Tiles',
    },
    {
      id: '3068a',
      name: 'Tile 2 x 2 without Groove',
      category: 'Tiles',
    },
    {
      id: '3069b',
      name: 'Tile 1 x 2 with Groove',
      category: 'Tiles',
    },
    {
      id: '3069a',
      name: 'Tile 1 x 2 without Groove',
      category: 'Tiles',
    },
    {
      id: '3070b',
      name: 'Tile 1 x 1 with Groove',
      category: 'Tiles',
    },
    {
      id: '3070a',
      name: 'Tile 1 x 1 without Groove',
      category: 'Tiles',
    },
    {
      id: '4162',
      name: 'Tile 1 x 8 with Groove',
      category: 'Tiles',
    },
    {
      id: '4974',
      name: 'Tile 8 x 16 with Smooth Surface',
      category: 'Tiles',
    },
    {
      id: '6320',
      name: 'Tile 6 x 8',
      category: 'Tiles',
    },
    {
      id: '6636',
      name: 'Tile 1 x 6 with Groove',
      category: 'Tiles',
    },
    {
      id: '6881b',
      name: 'Tile 6 x 6 with Central Bottom Tube',
      category: 'Tiles',
    },
    {
      id: '6881a',
      name: 'Tile 6 x 6 without Bottom Tubes',
      category: 'Tiles',
    },
    {
      id: '10202',
      name: 'Tile 6 x 6 with Bottom Tubes',
      category: 'Tiles',
    },
    {
      id: '14719',
      name: 'Tile 2 x 2 Corner',
      category: 'Tiles',
    },
    {
      id: '26603',
      name: 'Tile 2 x 3',
      category: 'Tiles',
    },
    {
      id: '48288',
      name: 'Tile 8 x 16 with Bottom Tubes on Edges',
      category: 'Tiles',
    },
    {
      id: '63864',
      name: 'Tile 1 x 3',
      category: 'Tiles',
    },
    {
      id: '69729',
      name: 'Tile 2 x 6',
      category: 'Tiles',
    },
    {
      id: '87079',
      name: 'Tile 2 x 4 with Groove',
      category: 'Tiles',
    },
    {
      id: '90498',
      name: 'Tile 8 x 16 with Bottom Tubes',
      category: 'Tiles',
    },
  ],
  'Bricks Round and Cones': [
    {
      id: '272',
      name: 'Cone 4 x 4 x 3 with Single Solid Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '716',
      name: 'Brick Round Corner 2 x 4 Half Round with Cutouts',
      category: 'Bricks Round and Cones',
    },
    {
      id: '1744',
      name: 'Cone 3 x 3 x 3 (Elliptic Paraboloid) with Internal Axle Hole',
      category: 'Bricks Round and Cones',
    },
    {
      id: '1746',
      name: 'Tower Roof 4 x 8 x 6 Half Cone Shaped with Roof Tiles',
      category: 'Bricks Round and Cones',
    },
    {
      id: '1871',
      name: 'Brick Round Curved 1 x 1 x 1 1/3 Quarter Dome',
      category: 'Bricks Round and Cones',
    },
    {
      id: '1974',
      name: 'Dome Hemisphere 7 x 7 with 2 Pin Holes [Plain]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '2577',
      name: 'Brick Round Corner 4 x 4 Full Brick',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3062b',
      name: 'Brick Round 1 x 1 Open Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3062a',
      name: 'Brick Round 1 x 1 Solid Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3063b',
      name: 'Brick Round Corner 2 x 2 Macaroni with Stud Notch',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3063a',
      name: 'Brick Round Corner 2 x 2 Macaroni without Stud Notch',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3262',
      name: 'Brick Round 2 x 2 Dome Top, Vented Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3569',
      name: 'Cone 4 x 4 x 3 with Axle Hole',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3941',
      name: 'Brick Round 2 x 2 with Axle Hole',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3942b',
      name: 'Cone 2 x 2 x 2, Blocked Open Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3942c',
      name: 'Cone 2 x 2 x 2, Open Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3942a',
      name: 'Cone 2 x 2 x 2, Solid Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3943b',
      name: 'Cone 4 x 4 x 2, Axle Hole [Plain]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '3943a',
      name: 'Cone 4 x 4 x 2, No Axle Hole',
      category: 'Bricks Round and Cones',
    },
    {
      id: '4588',
      name: 'Brick Round 1 x 1 with Fins, Open Stud',
      category: 'Bricks Round and Cones',
    },
    {
      id: '4589',
      name: 'Cone 1 x 1 [No Top Groove]',
      category: 'Bricks Round and Cones',
    },
    {
      id: '4591',
      name: 'Brick Round 2 x 2 x 2 with Axle Hole and Fins',
      category: 'Bricks Round and Cones',
    },
    {
      id: '4742',
      name: 'Cone 4 x 4 x 2 Hollow No Studs',
      category: 'Bricks Round and Cones',
    },
    {
      id: '4770',
      name: 'Brick Round 1 x 1 x 2/3 Light Bulb Cover',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5152',
      name: 'Brick Round Corner 3 x 3 Macaroni with 2 Studs',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5331',
      name: 'Brick Round 2 x 2 x 2 Crystal Facets Top',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5651',
      name: 'Brick Round Corner 4 x 4 x 1',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5848',
      name: 'Brick Round Curved 1 x 1 x 1 Quarter Dome',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5852',
      name: 'Brick Round Corner, Curved 2 x 2 x 2/3 Quarter Circle',
      category: 'Bricks Round and Cones',
    },
    {
      id: '5906',
      name: 'Brick Round Corner, Curved 2 x 2 x 1 2/3 Quarter Dome with 1 Cutout',
      category: 'Bricks Round and Cones',
    },
  ],
  'Plates Round Curved and Dishes': [
    {
      id: '712',
      name: 'Plate Round Corner Left 4 x 8 4 x 8 Left',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '712b',
      name: 'Plate Round Corner Left 4 x 8 with Round Bottom Studs and 2 Notches',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '712a',
      name: 'Plate Round Corner Left 4 x 8 with Waffle Bottom',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '713',
      name: 'Plate Round Corner Right 4 x 8',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '713b',
      name: 'Plate Round Corner Right 4 x 8 with Round Bottom Studs and 2 Notches',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '713a',
      name: 'Plate Round Corner Right 4 x 8 with Waffle Bottom',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '2654',
      name: 'Plate Round 2 x 2 with Rounded Bottom [Boat Stud]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '3263',
      name: 'Plate Round Corners Double 3 x 4 with 1 x 4 Raised Edge Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '3766',
      name: 'Plate Round 4 x 6',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '3960',
      name: 'Dish 4 x 4 Inverted [Radar]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '3961',
      name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Rounded Anti-stud Underside',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4032a',
      name: 'Plate Round 2 x 2 with Axle Hole Type 1 (+ Opening)',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4032b',
      name: 'Plate Round 2 x 2 with Axle Hole Type 2 (X Opening)',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4285b',
      name: 'Dish 6 x 6 Inverted, Radar / Webbed [Anti-studs at 90°]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4285a',
      name: 'Dish 6 x 6 Inverted, Radar / Webbed [No Anti-studs]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '4740',
      name: 'Dish 2 x 2 Inverted [Radar]',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '6003',
      name: 'Plate Round Corner 6 x 6',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '6141',
      name: 'Plate Round 1 x 1 with Solid Stud',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '6942',
      name: 'Dish 5 x 5',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '7864',
      name: 'Plate 4 x 4 with Rounded Corners, Pin Holes between Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '11213',
      name: 'Plate Round 6 x 6 with Hole',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '11833',
      name: 'Plate Round 4 x 4 with 2 x 2 Round Opening',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '15470',
      name: 'Plate Round 1 x 1 Swirled Top',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '18646',
      name: 'Plate Round Half 3 x 6 with 1 x 2 Cutout',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '18859',
      name: 'Dish 8 x 8 Inverted [Radar], Hollow Studs',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '18980',
      name: 'Plate Round Corners 2 x 6 Double',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '22888',
      name: 'Plate Round Half 4 x 8',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '30357',
      name: 'Plate Round Corner 3 x 3',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '30565',
      name: 'Plate Round Corner 4 x 4',
      category: 'Plates Round Curved and Dishes',
    },
    {
      id: '35044',
      name: 'Plate Special 4 x 4 with 3 x 3 Quarter Round Cutout',
      category: 'Plates Round Curved and Dishes',
    },
  ],
  'Bricks Curved': [
    {
      id: '1750',
      name: 'Slope Curved 2 x 2 Inverted with 1 x 2 Cutouts',
      category: 'Bricks Curved',
    },
    {
      id: '2339',
      name: 'Brick Arch 1 x 5 x 4 [Continuous Bow]',
      category: 'Bricks Curved',
    },
    {
      id: '3307',
      name: 'Brick Arch 1 x 6 x 2 - Thick Top with Reinforced Underside',
      category: 'Bricks Curved',
    },
    {
      id: '3308',
      name: 'Brick Arch 1 x 8 x 2',
      category: 'Bricks Curved',
    },
    {
      id: '3455',
      name: 'Brick Arch 1 x 6',
      category: 'Bricks Curved',
    },
    {
      id: '3563',
      name: 'Brick Curved 1 x 2 x 2/3 Double Curved Top, No Studs',
      category: 'Bricks Curved',
    },
    {
      id: '3572',
      name: 'Brick Arch 1 x 5 x 2',
      category: 'Bricks Curved',
    },
    {
      id: '3573',
      name: 'Slope Curved 1 x 4 x 1 2/3 No Studs',
      category: 'Bricks Curved',
    },
    {
      id: '3659',
      name: 'Brick Arch 1 x 4',
      category: 'Bricks Curved',
    },
    {
      id: '4045',
      name: 'Brick Curved 1 x 4 x 1 Rounded Ends',
      category: 'Bricks Curved',
    },
    {
      id: '4088',
      name: 'Brick Curved 1 x 4 x 2 Centre Stud Top',
      category: 'Bricks Curved',
    },
    {
      id: '4490',
      name: 'Brick Arch 1 x 3',
      category: 'Bricks Curved',
    },
    {
      id: '4743',
      name: 'Brick Arch 2 x 8 x 3',
      category: 'Bricks Curved',
    },
    {
      id: '4744',
      name: 'Brick Curved 2 x 4 x 2 Double [Plain]',
      category: 'Bricks Curved',
    },
    {
      id: '5093',
      name: 'Slope Curved 2 x 2 with Stud Notch Right',
      category: 'Bricks Curved',
    },
    {
      id: '5095',
      name: 'Slope Curved 2 x 2 with Stud Notch Left',
      category: 'Bricks Curved',
    },
    {
      id: '5841',
      name: 'Brick Curved 1 x 2 x 1 with Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '5842',
      name: 'Brick Curved 2 x 4 x 1',
      category: 'Bricks Curved',
    },
    {
      id: '5843',
      name: 'Brick Arch 1 x 3 x 1 2/3 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '5845',
      name: 'Brick Arch 1 x 5 x 3 1/3 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '5846',
      name: 'Brick Curved 2 x 2 x 1 Curved Top, Corner',
      category: 'Bricks Curved',
    },
    {
      id: '5847',
      name: 'Slope Curved 1 x 2 Inverted with 1 x 1 Cutouts',
      category: 'Bricks Curved',
    },
    {
      id: '5849',
      name: 'Brick Curved 1 x 4 x 1',
      category: 'Bricks Curved',
    },
    {
      id: '5850',
      name: 'Brick Arch 1 x 3 x 2, Straight End',
      category: 'Bricks Curved',
    },
    {
      id: '5854',
      name: 'Slope Curved 2 x 2 with 1 x 2 Cutouts',
      category: 'Bricks Curved',
    },
    {
      id: '5907',
      name: 'Brick Curved 1 x 2 x 1 2/3 with 1 Cutout',
      category: 'Bricks Curved',
    },
    {
      id: '6005',
      name: 'Brick Arch 1 x 3 x 2 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '6060',
      name: 'Brick Arch 1 x 6 x 3 1/3 Curved Top',
      category: 'Bricks Curved',
    },
    {
      id: '6081',
      name: 'Brick Curved 2 x 4 x 1 1/3',
      category: 'Bricks Curved',
    },
    {
      id: '6091',
      name: 'Brick Curved 1 x 2 x 1 1/3 with Curved Top',
      category: 'Bricks Curved',
    },
  ],
  'Plates Angled': [
    {
      id: '2401',
      name: 'Wedge Plate 10 x 10 with 4x4 Cutout and Cut Corner',
      category: 'Plates Angled',
    },
    {
      id: '2413',
      name: 'Wedge Plate 4 x 9 without Stud Notches',
      category: 'Plates Angled',
    },
    {
      id: '2419',
      name: 'Wedge Plate 3 x 6 Cut Corners',
      category: 'Plates Angled',
    },
    {
      id: '2450',
      name: 'Wedge Plate 3 x 3 Cut Corner',
      category: 'Plates Angled',
    },
    {
      id: '2621',
      name: 'Wedge Plate 9 x 10 Boat Bow',
      category: 'Plates Angled',
    },
    {
      id: '2625',
      name: 'Wedge Plate 7 x 6 Boat Bow without Stud Notches',
      category: 'Plates Angled',
    },
    {
      id: '3474',
      name: 'Wedge Plate 4 x 8 Tail',
      category: 'Plates Angled',
    },
    {
      id: '3544',
      name: 'Wedge Plate 8 x 3, 8° Left',
      category: 'Plates Angled',
    },
    {
      id: '3545',
      name: 'Wedge Plate 8 x 3, 8° Right',
      category: 'Plates Angled',
    },
    {
      id: '3585',
      name: 'Wedge, Plate 7 x 12 Wing Right',
      category: 'Plates Angled',
    },
    {
      id: '3586',
      name: 'Wedge, Plate 7 x 12 Wing Left',
      category: 'Plates Angled',
    },
    {
      id: '3933',
      name: 'Wedge Plate 8 x 4 Wing Left',
      category: 'Plates Angled',
    },
    {
      id: '3934',
      name: 'Wedge Plate 8 x 4 Wing Right',
      category: 'Plates Angled',
    },
    {
      id: '3935',
      name: 'Wedge Plate 4 x 4 Wing Right',
      category: 'Plates Angled',
    },
    {
      id: '3936',
      name: 'Wedge Plate 4 x 4 Wing Left',
      category: 'Plates Angled',
    },
    {
      id: '4475',
      name: 'Wedge, Plate 8 x 8 with 4 x 4 Cutout',
      category: 'Plates Angled',
    },
    {
      id: '4859',
      name: 'Wedge Plate 3 x 4 without Stud Notches',
      category: 'Plates Angled',
    },
    {
      id: '6104',
      name: 'Wedge Plate 8 x 8 with 3 x 4 Cutout',
      category: 'Plates Angled',
    },
    {
      id: '6106',
      name: 'Wedge Plate 6 x 6 Cut Corner',
      category: 'Plates Angled',
    },
    {
      id: '6219',
      name: 'Wedge, Plate 16 x 14 Shuttle',
      category: 'Plates Angled',
    },
    {
      id: '14181',
      name: 'Wedge Plate 4 x 9 with Stud Notches',
      category: 'Plates Angled',
    },
    {
      id: '15706',
      name: 'Wedge Plate 4 Stud 45° Angle Plate',
      category: 'Plates Angled',
    },
    {
      id: '24299',
      name: 'Wedge Plate 2 x 2 Left',
      category: 'Plates Angled',
    },
    {
      id: '24307',
      name: 'Wedge Plate 2 x 2 Right',
      category: 'Plates Angled',
    },
    {
      id: '26601',
      name: 'Wedge Plate 2 x 2 Cut Corner',
      category: 'Plates Angled',
    },
    {
      id: '30037',
      name: 'Wing Plate Bi-level 12 x 9 (Exploriens)',
      category: 'Plates Angled',
    },
    {
      id: '30118',
      name: 'Wing Plate Bi-level 8 x 4 and 2 x 3 1/3 Up',
      category: 'Plates Angled',
    },
    {
      id: '30119',
      name: 'Wing Plate Bi-level 8 x 4 and 2 x 3 1/3 Down',
      category: 'Plates Angled',
    },
    {
      id: '30355',
      name: 'Wedge Plate 6 x 12 Left',
      category: 'Plates Angled',
    },
    {
      id: '30356',
      name: 'Wedge Plate 6 x 12 Right',
      category: 'Plates Angled',
    },
  ],
  'Tiles Round and Curved': [
    {
      id: '1126',
      name: 'Tile Round 1 x 2',
      category: 'Tiles Round and Curved',
    },
    {
      id: '1748',
      name: 'Tile Round 1 x 2 Half Circle',
      category: 'Tiles Round and Curved',
    },
    {
      id: '4150',
      name: 'Tile Round 2 x 2 with Bottom Cross',
      category: 'Tiles Round and Curved',
    },
    {
      id: '5520',
      name: 'Tile Round 2 x 2 Half Circle',
      category: 'Tiles Round and Curved',
    },
    {
      id: '7212',
      name: 'Tile Round 6 x 6',
      category: 'Tiles Round and Curved',
    },
    {
      id: '7836',
      name: 'Tile 2 x 2 Curved, Macaroni, Center Anti-Stud',
      category: 'Tiles Round and Curved',
    },
    {
      id: '14769',
      name: 'Tile Round 2 x 2 with Bottom Stud Holder',
      category: 'Tiles Round and Curved',
    },
    {
      id: '24246',
      name: 'Tile Round 1 x 1 Half Circle',
      category: 'Tiles Round and Curved',
    },
    {
      id: '25269',
      name: 'Tile Round 1 x 1 Quarter',
      category: 'Tiles Round and Curved',
    },
    {
      id: '27507',
      name: 'Tile 4 x 4 Curved, Macaroni',
      category: 'Tiles Round and Curved',
    },
    {
      id: '27925',
      name: 'Tile 2 x 2 Curved, Macaroni',
      category: 'Tiles Round and Curved',
    },
    {
      id: '39739',
      name: 'Tile 1 x 1 Heart',
      category: 'Tiles Round and Curved',
    },
    {
      id: '65474',
      name: 'Tile 6 x 8 with Rounded Corners',
      category: 'Tiles Round and Curved',
    },
    {
      id: '66857',
      name: 'Tile Round 2 x 4',
      category: 'Tiles Round and Curved',
    },
    {
      id: '67095',
      name: 'Tile Round 3 x 3',
      category: 'Tiles Round and Curved',
    },
    {
      id: '68869',
      name: 'Tile Round Corners 4 x 4 x 2/3',
      category: 'Tiles Round and Curved',
    },
    {
      id: '79393',
      name: 'Tile 3 x 3 Curved, Macaroni',
      category: 'Tiles Round and Curved',
    },
    {
      id: '98138',
      name: 'Tile Round 1 x 1',
      category: 'Tiles Round and Curved',
    },
  ],
};

export const RebrickableColors = [
  {
    id: '0',
    name: 'Black',
    rgb: '05131D',
  },
  {
    id: '15',
    name: 'White',
    rgb: 'FFFFFF',
  },
  {
    id: '71',
    name: 'Light Bluish Gray',
    rgb: 'A0A5A9',
  },
  {
    id: '72',
    name: 'Dark Bluish Gray',
    rgb: '6C6E68',
  },
  {
    id: '4',
    name: 'Red',
    rgb: 'C91A09',
  },
  {
    id: '14',
    name: 'Yellow',
    rgb: 'F2CD37',
  },
  {
    id: '1',
    name: 'Blue',
    rgb: '0055BF',
  },
  {
    id: '19',
    name: 'Tan',
    rgb: 'E4CD9E',
  },
  {
    id: '70',
    name: 'Reddish Brown',
    rgb: '582A12',
  },
  {
    id: '7',
    name: 'Light Gray',
    rgb: '9BA19D',
  },
  {
    id: '2',
    name: 'Green',
    rgb: '237841',
  },
  {
    id: '28',
    name: 'Dark Tan',
    rgb: '958A73',
  },
  {
    id: '25',
    name: 'Orange',
    rgb: 'FE8A18',
  },
  {
    id: '272',
    name: 'Dark Blue',
    rgb: '0A3463',
  },
  {
    id: '297',
    name: 'Pearl Gold',
    rgb: 'AA7F2E',
  },
  {
    id: '320',
    name: 'Dark Red',
    rgb: '720E0F',
  },
  {
    id: '27',
    name: 'Lime',
    rgb: 'BBE90B',
  },
  {
    id: '84',
    name: 'Medium Nougat',
    rgb: 'AA7D55',
  },
  {
    id: '191',
    name: 'Bright Light Orange',
    rgb: 'F8BB3D',
  },
  {
    id: '322',
    name: 'Medium Azure',
    rgb: '36AEBF',
  },
  {
    id: '484',
    name: 'Dark Orange',
    rgb: 'A95500',
  },
  {
    id: '10',
    name: 'Bright Green',
    rgb: '4B9F4A',
  },
  {
    id: '288',
    name: 'Dark Green',
    rgb: '184632',
  },
  {
    id: '378',
    name: 'Sand Green',
    rgb: 'A0BCAC',
  },
  {
    id: '308',
    name: 'Dark Brown',
    rgb: '352100',
  },
  {
    id: '3',
    name: 'Dark Turquoise',
    rgb: '008F9B',
  },
  {
    id: '179',
    name: 'Flat Silver',
    rgb: '898788',
  },
  {
    id: '8',
    name: 'Dark Gray',
    rgb: '6D6E5C',
  },
  {
    id: '29',
    name: 'Bright Pink',
    rgb: 'E4ADC8',
  },
  {
    id: '85',
    name: 'Dark Purple',
    rgb: '3F3691',
  },
];

export const RebrickablePartsFlat = [
  { id: '10a', name: 'Baseplate 24 x 32 with Rounded Corners', category: 'Baseplates' },
  { id: '10b', name: 'Baseplate 24 x 32 with Squared Corners', category: 'Baseplates' },
  { id: '184', name: 'Baseplate 16 x 18', category: 'Baseplates' },
  { id: '210', name: 'Baseplate 16 x 22', category: 'Baseplates' },
  {
    id: '309',
    name: 'Baseplate 32 x 32 Split with 2 x 14 Center Studs [Plain]',
    category: 'Baseplates',
  },
  { id: '367', name: 'Baseplate 24 x 24 with Studs on Edges', category: 'Baseplates' },
  { id: '374', name: 'Baseplate 16 x 32 with Rounded Corners [Plain]', category: 'Baseplates' },
  { id: '397', name: 'Baseplate 10 x 16', category: 'Baseplates' },
  { id: '455', name: 'Baseplate 16 x 24 with Rounded Corners', category: 'Baseplates' },
  { id: '606', name: 'Baseplate 32 x 32 with 9-Stud Straight [Plain]', category: 'Baseplates' },
  { id: '607', name: 'Baseplate 32 x 32 with 9-Stud Crossroads [Plain]', category: 'Baseplates' },
  {
    id: '608',
    name: 'Baseplate 32 x 32 with 9-Stud T Intersection [Plain]',
    category: 'Baseplates',
  },
  { id: '609', name: 'Baseplate 32 x 32 with 9-Stud Curve [Plain]', category: 'Baseplates' },
  {
    id: '648',
    name: 'Baseplate 16 x 32 with Railway Station Stud Print [342]',
    category: 'Baseplates',
  },
  { id: '700', name: 'Thin Baseplate 10 x 20 x 0.5', category: 'Baseplates' },
  { id: '785', name: 'Baseplate 24 x 32 with Studs on Edges', category: 'Baseplates' },
  {
    id: '809',
    name: 'Baseplate 24 x 40 Gravel Quarry with Sets 360 / 580 Dots Print',
    category: 'Baseplates',
  },
  { id: '811', name: 'Baseplate 16 x 32 with Warehouse Stud Print [341]', category: 'Baseplates' },
  {
    id: '820',
    name: 'Baseplate Raised 8 x 18 with Garage Floor Plate (Old style)',
    category: 'Baseplates',
  },
  { id: '896', name: 'Baseplate 14 x 20 with Rounded Corners [Plain]', category: 'Baseplates' },
  { id: '0901', name: 'Baseplate 16 x 30 with Set 080 Yellow House Print', category: 'Baseplates' },
  {
    id: '0902',
    name: 'Baseplate 16 x 24 with Set 080 Small White House Print',
    category: 'Baseplates',
  },
  { id: '0903', name: 'Baseplate 16 x 24 with Set 080 Red House Print', category: 'Baseplates' },
  {
    id: '0904',
    name: 'Baseplate 16 x 24 with Set 080 Large White House Print',
    category: 'Baseplates',
  },
  {
    id: '911',
    name: 'Baseplate 10 x 48 Train Ferry, Reduced Studs at Center [343-1]',
    category: 'Baseplates',
  },
  { id: '912', name: 'Baseplate 16 x 16 Control Tower Set 340', category: 'Baseplates' },
  {
    id: '2552',
    name: 'Baseplate Raised 32 x 32 with Ramp and Pit [Plain]',
    category: 'Baseplates',
  },
  { id: '2617', name: 'Baseplate Raised 16 x 16 x 2 1/3 Platform', category: 'Baseplates' },
  { id: '2642', name: 'Baseplate Raised 16 x 16 x 2 1/3 Ramp', category: 'Baseplates' },
  { id: '3334', name: 'Baseplate 16 x 24', category: 'Baseplates' },
  { id: '678', name: 'Homemaker Awning 2 x 6', category: 'Bricks Sloped' },
  { id: '962', name: 'Slope 45° 2 x 2 Double Convex / Double Concave', category: 'Bricks Sloped' },
  { id: '1762', name: 'Slope 33° 2 x 2 Double / Inverted', category: 'Bricks Sloped' },
  { id: '2310', name: 'Slope 45° 2 x 1 Inverted with 2/3 Cutout', category: 'Bricks Sloped' },
  {
    id: '2341',
    name: 'Slope Inverted 45° 3 x 1 Double with 2 Completely Open Studs',
    category: 'Bricks Sloped',
  },
  { id: '2449', name: 'Slope Inverted 75° 2 x 1 x 3', category: 'Bricks Sloped' },
  { id: '2875', name: 'Slope 45° 2 x 6 x 2/3', category: 'Bricks Sloped' },
  { id: '2937', name: 'Slope 55° 1 x 6 x 5 with Bottom Stud Holders', category: 'Bricks Sloped' },
  { id: '3037', name: 'Slope 45° 2 x 4', category: 'Bricks Sloped' },
  { id: '3038', name: 'Slope 45° 2 x 3', category: 'Bricks Sloped' },
  { id: '3039', name: 'Slope 45° 2 x 2', category: 'Bricks Sloped' },
  { id: '3040b', name: 'Slope 45° 2 x 1 with Bottom Pin', category: 'Bricks Sloped' },
  { id: '3040a', name: 'Slope 45° 2 x 1 without Bottom Pin', category: 'Bricks Sloped' },
  { id: '3041', name: 'Slope 45° 2 x 4 Double', category: 'Bricks Sloped' },
  { id: '3042', name: 'Slope 45° 2 x 3 Double', category: 'Bricks Sloped' },
  { id: '3043', name: 'Slope 45° 2 x 2 Double', category: 'Bricks Sloped' },
  {
    id: '3044c',
    name: 'Slope 45° 2 x 1 Double with Inside Stud Holder',
    category: 'Bricks Sloped',
  },
  { id: '3044b', name: 'Slope 45° 2 x 1 Double with Ovoid Bottom Pin', category: 'Bricks Sloped' },
  { id: '3044a', name: 'Slope 45° 2 x 1 Double without Bottom Pin', category: 'Bricks Sloped' },
  { id: '3045', name: 'Slope 45° 2 x 2 Double Convex', category: 'Bricks Sloped' },
  { id: '3048b', name: 'Slope 45° 2 x 1 Triple Smooth', category: 'Bricks Sloped' },
  { id: '3048a', name: 'Slope 45° 2 x 1 Triple with Hollow Underside', category: 'Bricks Sloped' },
  {
    id: '3049d',
    name: 'Slope 45° 2 x 1 Double / Inverted with Bottom Stud Holder',
    category: 'Bricks Sloped',
  },
  {
    id: '3049a',
    name: 'Slope 45° 2 x 1 Double / Inverted with Bottom Tube',
    category: 'Bricks Sloped',
  },
  {
    id: '3049c',
    name: 'Slope 45° 2 x 1 Double / Inverted with Hollow Bottom',
    category: 'Bricks Sloped',
  },
  { id: '3297', name: 'Slope 33° 3 x 4', category: 'Bricks Sloped' },
  { id: '3298', name: 'Slope 33° 3 x 2', category: 'Bricks Sloped' },
  { id: '3299', name: 'Slope 33° 2 x 4 Double', category: 'Bricks Sloped' },
  { id: '3300', name: 'Slope 33° 2 x 2 Double', category: 'Bricks Sloped' },
  {
    id: '3660',
    name: 'Slope Inverted 45° 2 x 2 [Ovoid Bottom Pin, Bar-sized Stud Holes]',
    category: 'Bricks Sloped',
  },
  { id: '2336', name: 'Brick Special, Cockpit Space Nose', category: 'Bricks Special' },
  { id: '2434', name: 'Brick Special 2 x 4 x 2 with Studs on Sides', category: 'Bricks Special' },
  { id: '2458', name: 'Brick Special 1 x 2 with Pin', category: 'Bricks Special' },
  { id: '2653', name: 'Brick Special 1 x 4 with Groove', category: 'Bricks Special' },
  {
    id: '2832',
    name: 'Brick Special 2 x 8 x 5/6 with No Top Studs, and Channel on Ends, and Stud Holes on Sides',
    category: 'Bricks Special',
  },
  {
    id: '2833',
    name: 'Brick Special 1 x 8 x 5/6 with No Top Studs and Channel on Ends',
    category: 'Bricks Special',
  },
  { id: '2877', name: 'Brick Special 1 x 2 with Grille', category: 'Bricks Special' },
  { id: '2921', name: 'Brick Special 1 x 1 with Handle', category: 'Bricks Special' },
  {
    id: '3134',
    name: 'Brick Special 1 x 2 with Cable Holding Square Cutout',
    category: 'Bricks Special',
  },
  {
    id: '3487',
    name: 'Brick Special 8 x 10 x 2 with 6 x 10 Recessed, Pin Holes',
    category: 'Bricks Special',
  },
  { id: '3581', name: 'Brick Special 1 x 1 x 2 with Shutter Holder', category: 'Bricks Special' },
  {
    id: '3668',
    name: 'Brick Special 2 x 6 x 1 1/3 with Axle Holes and 2 x 4 Recessed, Ridges at Underside',
    category: 'Bricks Special',
  },
  { id: '4070', name: 'Brick Special 1 x 1 with Headlight', category: 'Bricks Special' },
  { id: '4216', name: 'Brick Special 1 x 2 with Groove', category: 'Bricks Special' },
  { id: '4217', name: 'Brick Special 1 x 14 Grooved', category: 'Bricks Special' },
  { id: '4595', name: 'Brick Special 1 x 2 x 2/3 with Studs on Sides', category: 'Bricks Special' },
  { id: '4729', name: 'Brick Special 2 x 2 No Studs, Top Pin', category: 'Bricks Special' },
  { id: '4730', name: 'Brick Special 2 x 2 with Pin and No Axle Hole', category: 'Bricks Special' },
  { id: '4732', name: 'Bracket 8 x 2 x 1 1/3', category: 'Bricks Special' },
  { id: '4733', name: 'Brick Special 1 x 1 Studs on 4 Sides', category: 'Bricks Special' },
  { id: '4747', name: 'Brick Special 2 x 4 with Coupling, Male', category: 'Bricks Special' },
  { id: '4748', name: 'Brick Special 2 x 4 with Coupling, Female', category: 'Bricks Special' },
  { id: '4920', name: 'Brick Special 1 x 2 with Rotation Joint Pin', category: 'Bricks Special' },
  { id: '5712', name: 'Bracket 5 x 1 x 1 1/3', category: 'Bricks Special' },
  { id: '6032', name: 'Brick Special Octagonal 2 x 3 x 1 2/3 Sloped', category: 'Bricks Special' },
  { id: '6037', name: 'Brick Special Octagonal 2 x 2 x 3 1/3', category: 'Bricks Special' },
  {
    id: '6042',
    name: 'Brick Special Octagonal 2 x 2 x 3 1/3 with Side Studs',
    category: 'Bricks Special',
  },
  { id: '6043', name: 'Brick Special Octagonal 2 x 2 x 3 1/3 Corner', category: 'Bricks Special' },
  { id: '6056', name: 'Brick Special 2 x 2 x 6 with Groove', category: 'Bricks Special' },
  { id: '6061', name: 'Brick 2 x 4 x 2 with Holes on Sides', category: 'Bricks Special' },
  {
    id: '422',
    name: 'Plate Special 2 x 2 with Small Holes for Metal Axle',
    category: 'Plates Special',
  },
  { id: '709', name: 'Plate Special 4 x 6 with Hole', category: 'Plates Special' },
  { id: '711', name: 'Plate Special 5 x 6 with Hole', category: 'Plates Special' },
  {
    id: '737',
    name: 'Plate Special 2 x 4 with Train Coupler Closed for Hook',
    category: 'Plates Special',
  },
  {
    id: '753',
    name: 'Plate Special 2 x 4 with Train Coupler, Open for Magnet [Reinforced]',
    category: 'Plates Special',
  },
  {
    id: '967',
    name: 'Plate Special 4 x 8 with Helicopter Rotor Holder',
    category: 'Plates Special',
  },
  {
    id: '1745',
    name: 'Plate Round 1 x 2 Half Circle with Stud (Jumper)',
    category: 'Plates Special',
  },
  { id: '1942', name: 'Plate Special 2 x 4 Fresnel Lens', category: 'Plates Special' },
  { id: '2436', name: 'Bracket 1 x 2 - 1 x 4 [Square Corners]', category: 'Plates Special' },
  {
    id: '2444',
    name: 'Plate Special 2 x 2 with 1 Pin Hole [Split Underside Ribs]',
    category: 'Plates Special',
  },
  { id: '2476a', name: 'Plate Special 2 x 2 with Pin on Bottom', category: 'Plates Special' },
  {
    id: '2476b',
    name: 'Plate Special 2 x 2 with Pin on Bottom, Small Holes in Plate and Rotational Locking Fingers on Underside',
    category: 'Plates Special',
  },
  { id: '2508', name: 'Plate Special 1 x 2 with Long Towball', category: 'Plates Special' },
  {
    id: '2539',
    name: 'Plate Special 6 x 6 Octagonal with Square Hole and 4 Clips (Boat Mast Platform)',
    category: 'Plates Special',
  },
  { id: '2540', name: 'Plate Special 1 x 2 Side Handle [Free Ends]', category: 'Plates Special' },
  {
    id: '2612',
    name: 'Plate Special 16 x 16 x 2/3 with 7 Recessed Edges, 8 x 8 Cutout',
    category: 'Plates Special',
  },
  {
    id: '2628',
    name: 'Plate Special 8 x 8 x 2/3 with Four 1 x 4 Recessed Edges',
    category: 'Plates Special',
  },
  {
    id: '2629',
    name: 'Plate Special 8 x 16 x 2/3 with Six Recessed Edges',
    category: 'Plates Special',
  },
  { id: '2817', name: 'Plate Special 2 x 2 with 2 Pin Holes', category: 'Plates Special' },
  { id: '2926', name: 'Plate Special 1 x 4 with Wheels Holder', category: 'Plates Special' },
  {
    id: '3058a',
    name: 'Plate Special 6 x 16 with Motor Opening Narrow',
    category: 'Plates Special',
  },
  { id: '3058b', name: 'Plate Special 6 x 16 with Motor Opening Wide', category: 'Plates Special' },
  { id: '3170', name: 'Plate Special 1 x 2 with 2 End Towballs', category: 'Plates Special' },
  { id: '3172', name: 'Plate Special 1 x 2 with Pin Hole On Side', category: 'Plates Special' },
  { id: '3176', name: 'Plate Special 3 x 2 with Rounded End, Hole', category: 'Plates Special' },
  {
    id: '3183a',
    name: 'Plate Special 1 x 4 with Towball Socket, Long, 2 Slots',
    category: 'Plates Special',
  },
  {
    id: '3183b',
    name: 'Plate Special 1 x 4 with Towball Socket, Long, 4 Slots',
    category: 'Plates Special',
  },
  {
    id: '3183c',
    name: 'Plate Special 1 x 4 with Towball Socket, Short, 4 Slots',
    category: 'Plates Special',
  },
  { id: '3184', name: 'Plate Special 1 x 4 with Towball', category: 'Plates Special' },
  { id: '3386', name: 'Plate 1 x 1 x 2/3 Half Round with Side Stud', category: 'Plates Special' },
  {
    id: '700b',
    name: "Brick 10 x 20 without Bottom Tubes, with '+' Cross Support (early Baseplate)",
    category: 'Bricks',
  },
  {
    id: '700a',
    name: "Brick 10 x 20 without Bottom Tubes, with '+' Cross Support and 4 Side Supports (early Baseplate)",
    category: 'Bricks',
  },
  { id: '702', name: 'Brick 4 x 4 Corner', category: 'Bricks' },
  {
    id: '733',
    name: 'Brick 10 x 10 without Bottom Tubes, without Cross Supports',
    category: 'Bricks',
  },
  { id: '772', name: 'Brick 1 x 2 x 2 without Bottom Tube', category: 'Bricks' },
  { id: '2356', name: 'Brick 4 x 6', category: 'Bricks' },
  { id: '2357', name: 'Brick 2 x 2 Corner', category: 'Bricks' },
  { id: '2453a', name: 'Brick 1 x 1 x 5 with Blocked Open or Hollow Stud', category: 'Bricks' },
  { id: '2453b', name: 'Brick 1 x 1 x 5 with Solid Stud', category: 'Bricks' },
  {
    id: '2454a',
    name: 'Brick 1 x 2 x 5 with Blocked Open Studs and Bottom Stud Holder with Asymmetric Ridges',
    category: 'Bricks',
  },
  { id: '2454b', name: 'Brick 1 x 2 x 5 with Hollow Studs', category: 'Bricks' },
  { id: '2456', name: 'Brick 2 x 6', category: 'Bricks' },
  { id: '2465', name: 'Brick 1 x 16', category: 'Bricks' },
  { id: '3001', name: 'Brick 2 x 4', category: 'Bricks' },
  { id: '3001b', name: 'Brick 2 x 4 without Cross Supports, with Hole in Top', category: 'Bricks' },
  { id: '3002', name: 'Brick 2 x 3', category: 'Bricks' },
  { id: '3003', name: 'Brick 2 x 2', category: 'Bricks' },
  { id: '3004', name: 'Brick 1 x 2', category: 'Bricks' },
  { id: '3005', name: 'Brick 1 x 1', category: 'Bricks' },
  { id: '3006', name: 'Brick 2 x 10', category: 'Bricks' },
  { id: '3007', name: 'Brick 2 x 8', category: 'Bricks' },
  { id: '3008', name: 'Brick 1 x 8', category: 'Bricks' },
  { id: '3009', name: 'Brick 1 x 6', category: 'Bricks' },
  { id: '3010', name: 'Brick 1 x 4', category: 'Bricks' },
  { id: '3065', name: 'Brick 1 x 2 without Bottom Tube', category: 'Bricks' },
  { id: '3066', name: 'Brick 1 x 4 without Bottom Tubes', category: 'Bricks' },
  { id: '3067', name: 'Brick 1 x 6 with No Bottom Tubes', category: 'Bricks' },
  { id: '3245a', name: 'Brick 1 x 2 x 2 with Center Pin [Plain]', category: 'Bricks' },
  { id: '3245b', name: 'Brick 1 x 2 x 2 with Inside Axle Holder', category: 'Bricks' },
  { id: '3245c', name: 'Brick 1 x 2 x 2 with Inside Stud Holder', category: 'Bricks' },
  { id: '728', name: 'Plate 8 x 11', category: 'Plates' },
  { id: '2420', name: 'Plate 2 x 2 Corner', category: 'Plates' },
  { id: '2445', name: 'Plate 2 x 12', category: 'Plates' },
  { id: '2639', name: 'Plate 4 x 4 Corner', category: 'Plates' },
  { id: '3020', name: 'Plate 2 x 4', category: 'Plates' },
  { id: '3021', name: 'Plate 2 x 3', category: 'Plates' },
  { id: '3022', name: 'Plate 2 x 2', category: 'Plates' },
  { id: '3023', name: 'Plate 1 x 2', category: 'Plates' },
  { id: '3023a', name: 'Plate 1 x 2 [Old Style Bottom]', category: 'Plates' },
  { id: '3024', name: 'Plate 1 x 1', category: 'Plates' },
  { id: '3026', name: 'Plate 6 x 24', category: 'Plates' },
  { id: '3027', name: 'Plate 6 x 16', category: 'Plates' },
  { id: '3028', name: 'Plate 6 x 12', category: 'Plates' },
  { id: '3029', name: 'Plate 4 x 12', category: 'Plates' },
  { id: '3030', name: 'Plate 4 x 10', category: 'Plates' },
  { id: '3031', name: 'Plate 4 x 4', category: 'Plates' },
  { id: '3032', name: 'Plate 4 x 6', category: 'Plates' },
  { id: '3033', name: 'Plate 6 x 10', category: 'Plates' },
  { id: '3034', name: 'Plate 2 x 8', category: 'Plates' },
  { id: '3035', name: 'Plate 4 x 8', category: 'Plates' },
  { id: '3036', name: 'Plate 6 x 8', category: 'Plates' },
  { id: '3456', name: 'Plate 6 x 14', category: 'Plates' },
  { id: '3460', name: 'Plate 1 x 8', category: 'Plates' },
  { id: '3623', name: 'Plate 1 x 3', category: 'Plates' },
  { id: '3666', name: 'Plate 1 x 6', category: 'Plates' },
  { id: '3710', name: 'Plate 1 x 4', category: 'Plates' },
  { id: '3795', name: 'Plate 2 x 6', category: 'Plates' },
  { id: '3832', name: 'Plate 2 x 10', category: 'Plates' },
  { id: '3958', name: 'Plate 6 x 6', category: 'Plates' },
  { id: '4282', name: 'Plate 2 x 16', category: 'Plates' },
  { id: '2376', name: 'Tile Round 2 x 2 - Thin Lifting Ring', category: 'Tiles Special' },
  { id: '2412b', name: 'Tile Special 1 x 2 Grille with Bottom Groove', category: 'Tiles Special' },
  {
    id: '2412a',
    name: 'Tile Special 1 x 2 Grille without Bottom Groove',
    category: 'Tiles Special',
  },
  { id: '2432', name: 'Tile Special 1 x 2 with Handle', category: 'Tiles Special' },
  { id: '2460', name: 'Tile Special 2 x 2 with Top Pin', category: 'Tiles Special' },
  { id: '2555', name: 'Tile Special 1 x 1 with Clip and Straight Tips', category: 'Tiles Special' },
  {
    id: '3160',
    name: 'Tile 6 x 6 x 2/3, Angled Textured Surface (Ice)',
    category: 'Tiles Special',
  },
  { id: '3395', name: 'Tile Special 2 x 4 Inverted', category: 'Tiles Special' },
  {
    id: '3396',
    name: 'Tile Special 2 x 2 with 2 Quarter Round Cutouts',
    category: 'Tiles Special',
  },
  { id: '3567', name: 'Tile Special Round 2 x 2 Inverted', category: 'Tiles Special' },
  {
    id: '4092',
    name: 'Tile Special 6 x 4 with Beveled Edges and 7mm Pin (Train Bogie Plate)',
    category: 'Tiles Special',
  },
  { id: '5091', name: 'Tile 1 x 2 with Stud Notch Left', category: 'Tiles Special' },
  { id: '5092', name: 'Tile 1 x 2 with Stud Notch Right', category: 'Tiles Special' },
  { id: '6805', name: 'Tile Special 2 x 2 with Ring', category: 'Tiles Special' },
  { id: '7828', name: 'Wedge Tile 2 x 2 Left', category: 'Tiles Special' },
  { id: '7829', name: 'Wedge Tile 2 x 2 Right', category: 'Tiles Special' },
  { id: '11203', name: 'Tile Special 2 x 2 Inverted', category: 'Tiles Special' },
  { id: '11609', name: 'Tile, Star with Stud Holder, Pin Hole', category: 'Tiles Special' },
  {
    id: '12825',
    name: 'Tile Special 1 x 1 with Clip with Rounded Tips',
    category: 'Tiles Special',
  },
  {
    id: '15209',
    name: 'Tile Special 1 x 2 with Two Vertical Teeth / Tooth',
    category: 'Tiles Special',
  },
  { id: '15535', name: 'Tile Round 2 x 2 with Hole', category: 'Tiles Special' },
  {
    id: '15712',
    name: 'Tile Special 1 x 1 with Clip with Rounded Edges',
    category: 'Tiles Special',
  },
  { id: '20482', name: 'Tile Round 1 x 1 with Hollow Bar', category: 'Tiles Special' },
  { id: '22385', name: 'Tile Special 2 x 3 Pentagonal', category: 'Tiles Special' },
  { id: '24445', name: 'Tile Special 1 x 2 with Minifig Neck Pin', category: 'Tiles Special' },
  {
    id: '27263',
    name: 'Tile Special 2 x 2 Corner with Cut Corner - Facet',
    category: 'Tiles Special',
  },
  { id: '30256', name: 'Tile Special 2 x 2 with Bar and Stud', category: 'Tiles Special' },
  {
    id: '30350a',
    name: 'Tile Special 2 x 3 with 2 Clips [Angled Clips]',
    category: 'Tiles Special',
  },
  {
    id: '30350b',
    name: 'Tile Special 2 x 3 with 2 Clips [Thick Open O Clips]',
    category: 'Tiles Special',
  },
  {
    id: '30350c',
    name: 'Tile Special 2 x 3 with 2 Clips [Thick U Clips]',
    category: 'Tiles Special',
  },
  { id: '1751', name: 'Tile 4 x 4', category: 'Tiles' },
  { id: '2431', name: 'Tile 1 x 4 with Groove', category: 'Tiles' },
  { id: '3068b', name: 'Tile 2 x 2 with Groove', category: 'Tiles' },
  { id: '3068a', name: 'Tile 2 x 2 without Groove', category: 'Tiles' },
  { id: '3069b', name: 'Tile 1 x 2 with Groove', category: 'Tiles' },
  { id: '3069a', name: 'Tile 1 x 2 without Groove', category: 'Tiles' },
  { id: '3070b', name: 'Tile 1 x 1 with Groove', category: 'Tiles' },
  { id: '3070a', name: 'Tile 1 x 1 without Groove', category: 'Tiles' },
  { id: '4162', name: 'Tile 1 x 8 with Groove', category: 'Tiles' },
  { id: '4974', name: 'Tile 8 x 16 with Smooth Surface', category: 'Tiles' },
  { id: '6320', name: 'Tile 6 x 8', category: 'Tiles' },
  { id: '6636', name: 'Tile 1 x 6 with Groove', category: 'Tiles' },
  { id: '6881b', name: 'Tile 6 x 6 with Central Bottom Tube', category: 'Tiles' },
  { id: '6881a', name: 'Tile 6 x 6 without Bottom Tubes', category: 'Tiles' },
  { id: '10202', name: 'Tile 6 x 6 with Bottom Tubes', category: 'Tiles' },
  { id: '14719', name: 'Tile 2 x 2 Corner', category: 'Tiles' },
  { id: '26603', name: 'Tile 2 x 3', category: 'Tiles' },
  { id: '48288', name: 'Tile 8 x 16 with Bottom Tubes on Edges', category: 'Tiles' },
  { id: '63864', name: 'Tile 1 x 3', category: 'Tiles' },
  { id: '69729', name: 'Tile 2 x 6', category: 'Tiles' },
  { id: '87079', name: 'Tile 2 x 4 with Groove', category: 'Tiles' },
  { id: '90498', name: 'Tile 8 x 16 with Bottom Tubes', category: 'Tiles' },
  { id: '272', name: 'Cone 4 x 4 x 3 with Single Solid Stud', category: 'Bricks Round and Cones' },
  {
    id: '716',
    name: 'Brick Round Corner 2 x 4 Half Round with Cutouts',
    category: 'Bricks Round and Cones',
  },
  {
    id: '1744',
    name: 'Cone 3 x 3 x 3 (Elliptic Paraboloid) with Internal Axle Hole',
    category: 'Bricks Round and Cones',
  },
  {
    id: '1746',
    name: 'Tower Roof 4 x 8 x 6 Half Cone Shaped with Roof Tiles',
    category: 'Bricks Round and Cones',
  },
  {
    id: '1871',
    name: 'Brick Round Curved 1 x 1 x 1 1/3 Quarter Dome',
    category: 'Bricks Round and Cones',
  },
  {
    id: '1974',
    name: 'Dome Hemisphere 7 x 7 with 2 Pin Holes [Plain]',
    category: 'Bricks Round and Cones',
  },
  { id: '2577', name: 'Brick Round Corner 4 x 4 Full Brick', category: 'Bricks Round and Cones' },
  { id: '3062b', name: 'Brick Round 1 x 1 Open Stud', category: 'Bricks Round and Cones' },
  { id: '3062a', name: 'Brick Round 1 x 1 Solid Stud', category: 'Bricks Round and Cones' },
  {
    id: '3063b',
    name: 'Brick Round Corner 2 x 2 Macaroni with Stud Notch',
    category: 'Bricks Round and Cones',
  },
  {
    id: '3063a',
    name: 'Brick Round Corner 2 x 2 Macaroni without Stud Notch',
    category: 'Bricks Round and Cones',
  },
  {
    id: '3262',
    name: 'Brick Round 2 x 2 Dome Top, Vented Stud',
    category: 'Bricks Round and Cones',
  },
  { id: '3569', name: 'Cone 4 x 4 x 3 with Axle Hole', category: 'Bricks Round and Cones' },
  { id: '3941', name: 'Brick Round 2 x 2 with Axle Hole', category: 'Bricks Round and Cones' },
  { id: '3942b', name: 'Cone 2 x 2 x 2, Blocked Open Stud', category: 'Bricks Round and Cones' },
  { id: '3942c', name: 'Cone 2 x 2 x 2, Open Stud', category: 'Bricks Round and Cones' },
  { id: '3942a', name: 'Cone 2 x 2 x 2, Solid Stud', category: 'Bricks Round and Cones' },
  { id: '3943b', name: 'Cone 4 x 4 x 2, Axle Hole [Plain]', category: 'Bricks Round and Cones' },
  { id: '3943a', name: 'Cone 4 x 4 x 2, No Axle Hole', category: 'Bricks Round and Cones' },
  {
    id: '4588',
    name: 'Brick Round 1 x 1 with Fins, Open Stud',
    category: 'Bricks Round and Cones',
  },
  { id: '4589', name: 'Cone 1 x 1 [No Top Groove]', category: 'Bricks Round and Cones' },
  {
    id: '4591',
    name: 'Brick Round 2 x 2 x 2 with Axle Hole and Fins',
    category: 'Bricks Round and Cones',
  },
  { id: '4742', name: 'Cone 4 x 4 x 2 Hollow No Studs', category: 'Bricks Round and Cones' },
  {
    id: '4770',
    name: 'Brick Round 1 x 1 x 2/3 Light Bulb Cover',
    category: 'Bricks Round and Cones',
  },
  {
    id: '5152',
    name: 'Brick Round Corner 3 x 3 Macaroni with 2 Studs',
    category: 'Bricks Round and Cones',
  },
  {
    id: '5331',
    name: 'Brick Round 2 x 2 x 2 Crystal Facets Top',
    category: 'Bricks Round and Cones',
  },
  { id: '5651', name: 'Brick Round Corner 4 x 4 x 1', category: 'Bricks Round and Cones' },
  {
    id: '5848',
    name: 'Brick Round Curved 1 x 1 x 1 Quarter Dome',
    category: 'Bricks Round and Cones',
  },
  {
    id: '5852',
    name: 'Brick Round Corner, Curved 2 x 2 x 2/3 Quarter Circle',
    category: 'Bricks Round and Cones',
  },
  {
    id: '5906',
    name: 'Brick Round Corner, Curved 2 x 2 x 1 2/3 Quarter Dome with 1 Cutout',
    category: 'Bricks Round and Cones',
  },
  {
    id: '712',
    name: 'Plate Round Corner Left 4 x 8 4 x 8 Left',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '712b',
    name: 'Plate Round Corner Left 4 x 8 with Round Bottom Studs and 2 Notches',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '712a',
    name: 'Plate Round Corner Left 4 x 8 with Waffle Bottom',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '713', name: 'Plate Round Corner Right 4 x 8', category: 'Plates Round Curved and Dishes' },
  {
    id: '713b',
    name: 'Plate Round Corner Right 4 x 8 with Round Bottom Studs and 2 Notches',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '713a',
    name: 'Plate Round Corner Right 4 x 8 with Waffle Bottom',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '2654',
    name: 'Plate Round 2 x 2 with Rounded Bottom [Boat Stud]',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '3263',
    name: 'Plate Round Corners Double 3 x 4 with 1 x 4 Raised Edge Studs',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '3766', name: 'Plate Round 4 x 6', category: 'Plates Round Curved and Dishes' },
  { id: '3960', name: 'Dish 4 x 4 Inverted [Radar]', category: 'Plates Round Curved and Dishes' },
  {
    id: '3961',
    name: 'Dish 8 x 8 Inverted [Radar], Solid Studs, Rounded Anti-stud Underside',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '4032a',
    name: 'Plate Round 2 x 2 with Axle Hole Type 1 (+ Opening)',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '4032b',
    name: 'Plate Round 2 x 2 with Axle Hole Type 2 (X Opening)',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '4285b',
    name: 'Dish 6 x 6 Inverted, Radar / Webbed [Anti-studs at 90°]',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '4285a',
    name: 'Dish 6 x 6 Inverted, Radar / Webbed [No Anti-studs]',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '4740', name: 'Dish 2 x 2 Inverted [Radar]', category: 'Plates Round Curved and Dishes' },
  { id: '6003', name: 'Plate Round Corner 6 x 6', category: 'Plates Round Curved and Dishes' },
  {
    id: '6141',
    name: 'Plate Round 1 x 1 with Solid Stud',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '6942', name: 'Dish 5 x 5', category: 'Plates Round Curved and Dishes' },
  {
    id: '7864',
    name: 'Plate 4 x 4 with Rounded Corners, Pin Holes between Studs',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '11213', name: 'Plate Round 6 x 6 with Hole', category: 'Plates Round Curved and Dishes' },
  {
    id: '11833',
    name: 'Plate Round 4 x 4 with 2 x 2 Round Opening',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '15470',
    name: 'Plate Round 1 x 1 Swirled Top',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '18646',
    name: 'Plate Round Half 3 x 6 with 1 x 2 Cutout',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '18859',
    name: 'Dish 8 x 8 Inverted [Radar], Hollow Studs',
    category: 'Plates Round Curved and Dishes',
  },
  {
    id: '18980',
    name: 'Plate Round Corners 2 x 6 Double',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '22888', name: 'Plate Round Half 4 x 8', category: 'Plates Round Curved and Dishes' },
  { id: '30357', name: 'Plate Round Corner 3 x 3', category: 'Plates Round Curved and Dishes' },
  { id: '30565', name: 'Plate Round Corner 4 x 4', category: 'Plates Round Curved and Dishes' },
  {
    id: '35044',
    name: 'Plate Special 4 x 4 with 3 x 3 Quarter Round Cutout',
    category: 'Plates Round Curved and Dishes',
  },
  { id: '1750', name: 'Slope Curved 2 x 2 Inverted with 1 x 2 Cutouts', category: 'Bricks Curved' },
  { id: '2339', name: 'Brick Arch 1 x 5 x 4 [Continuous Bow]', category: 'Bricks Curved' },
  {
    id: '3307',
    name: 'Brick Arch 1 x 6 x 2 - Thick Top with Reinforced Underside',
    category: 'Bricks Curved',
  },
  { id: '3308', name: 'Brick Arch 1 x 8 x 2', category: 'Bricks Curved' },
  { id: '3455', name: 'Brick Arch 1 x 6', category: 'Bricks Curved' },
  {
    id: '3563',
    name: 'Brick Curved 1 x 2 x 2/3 Double Curved Top, No Studs',
    category: 'Bricks Curved',
  },
  { id: '3572', name: 'Brick Arch 1 x 5 x 2', category: 'Bricks Curved' },
  { id: '3573', name: 'Slope Curved 1 x 4 x 1 2/3 No Studs', category: 'Bricks Curved' },
  { id: '3659', name: 'Brick Arch 1 x 4', category: 'Bricks Curved' },
  { id: '4045', name: 'Brick Curved 1 x 4 x 1 Rounded Ends', category: 'Bricks Curved' },
  { id: '4088', name: 'Brick Curved 1 x 4 x 2 Centre Stud Top', category: 'Bricks Curved' },
  { id: '4490', name: 'Brick Arch 1 x 3', category: 'Bricks Curved' },
  { id: '4743', name: 'Brick Arch 2 x 8 x 3', category: 'Bricks Curved' },
  { id: '4744', name: 'Brick Curved 2 x 4 x 2 Double [Plain]', category: 'Bricks Curved' },
  { id: '5093', name: 'Slope Curved 2 x 2 with Stud Notch Right', category: 'Bricks Curved' },
  { id: '5095', name: 'Slope Curved 2 x 2 with Stud Notch Left', category: 'Bricks Curved' },
  { id: '5841', name: 'Brick Curved 1 x 2 x 1 with Curved Top', category: 'Bricks Curved' },
  { id: '5842', name: 'Brick Curved 2 x 4 x 1', category: 'Bricks Curved' },
  { id: '5843', name: 'Brick Arch 1 x 3 x 1 2/3 Curved Top', category: 'Bricks Curved' },
  { id: '5845', name: 'Brick Arch 1 x 5 x 3 1/3 Curved Top', category: 'Bricks Curved' },
  { id: '5846', name: 'Brick Curved 2 x 2 x 1 Curved Top, Corner', category: 'Bricks Curved' },
  { id: '5847', name: 'Slope Curved 1 x 2 Inverted with 1 x 1 Cutouts', category: 'Bricks Curved' },
  { id: '5849', name: 'Brick Curved 1 x 4 x 1', category: 'Bricks Curved' },
  { id: '5850', name: 'Brick Arch 1 x 3 x 2, Straight End', category: 'Bricks Curved' },
  { id: '5854', name: 'Slope Curved 2 x 2 with 1 x 2 Cutouts', category: 'Bricks Curved' },
  { id: '5907', name: 'Brick Curved 1 x 2 x 1 2/3 with 1 Cutout', category: 'Bricks Curved' },
  { id: '6005', name: 'Brick Arch 1 x 3 x 2 Curved Top', category: 'Bricks Curved' },
  { id: '6060', name: 'Brick Arch 1 x 6 x 3 1/3 Curved Top', category: 'Bricks Curved' },
  { id: '6081', name: 'Brick Curved 2 x 4 x 1 1/3', category: 'Bricks Curved' },
  { id: '6091', name: 'Brick Curved 1 x 2 x 1 1/3 with Curved Top', category: 'Bricks Curved' },
  {
    id: '2401',
    name: 'Wedge Plate 10 x 10 with 4x4 Cutout and Cut Corner',
    category: 'Plates Angled',
  },
  { id: '2413', name: 'Wedge Plate 4 x 9 without Stud Notches', category: 'Plates Angled' },
  { id: '2419', name: 'Wedge Plate 3 x 6 Cut Corners', category: 'Plates Angled' },
  { id: '2450', name: 'Wedge Plate 3 x 3 Cut Corner', category: 'Plates Angled' },
  { id: '2621', name: 'Wedge Plate 9 x 10 Boat Bow', category: 'Plates Angled' },
  {
    id: '2625',
    name: 'Wedge Plate 7 x 6 Boat Bow without Stud Notches',
    category: 'Plates Angled',
  },
  { id: '3474', name: 'Wedge Plate 4 x 8 Tail', category: 'Plates Angled' },
  { id: '3544', name: 'Wedge Plate 8 x 3, 8° Left', category: 'Plates Angled' },
  { id: '3545', name: 'Wedge Plate 8 x 3, 8° Right', category: 'Plates Angled' },
  { id: '3585', name: 'Wedge, Plate 7 x 12 Wing Right', category: 'Plates Angled' },
  { id: '3586', name: 'Wedge, Plate 7 x 12 Wing Left', category: 'Plates Angled' },
  { id: '3933', name: 'Wedge Plate 8 x 4 Wing Left', category: 'Plates Angled' },
  { id: '3934', name: 'Wedge Plate 8 x 4 Wing Right', category: 'Plates Angled' },
  { id: '3935', name: 'Wedge Plate 4 x 4 Wing Right', category: 'Plates Angled' },
  { id: '3936', name: 'Wedge Plate 4 x 4 Wing Left', category: 'Plates Angled' },
  { id: '4475', name: 'Wedge, Plate 8 x 8 with 4 x 4 Cutout', category: 'Plates Angled' },
  { id: '4859', name: 'Wedge Plate 3 x 4 without Stud Notches', category: 'Plates Angled' },
  { id: '6104', name: 'Wedge Plate 8 x 8 with 3 x 4 Cutout', category: 'Plates Angled' },
  { id: '6106', name: 'Wedge Plate 6 x 6 Cut Corner', category: 'Plates Angled' },
  { id: '6219', name: 'Wedge, Plate 16 x 14 Shuttle', category: 'Plates Angled' },
  { id: '14181', name: 'Wedge Plate 4 x 9 with Stud Notches', category: 'Plates Angled' },
  { id: '15706', name: 'Wedge Plate 4 Stud 45° Angle Plate', category: 'Plates Angled' },
  { id: '24299', name: 'Wedge Plate 2 x 2 Left', category: 'Plates Angled' },
  { id: '24307', name: 'Wedge Plate 2 x 2 Right', category: 'Plates Angled' },
  { id: '26601', name: 'Wedge Plate 2 x 2 Cut Corner', category: 'Plates Angled' },
  { id: '30037', name: 'Wing Plate Bi-level 12 x 9 (Exploriens)', category: 'Plates Angled' },
  { id: '30118', name: 'Wing Plate Bi-level 8 x 4 and 2 x 3 1/3 Up', category: 'Plates Angled' },
  { id: '30119', name: 'Wing Plate Bi-level 8 x 4 and 2 x 3 1/3 Down', category: 'Plates Angled' },
  { id: '30355', name: 'Wedge Plate 6 x 12 Left', category: 'Plates Angled' },
  { id: '30356', name: 'Wedge Plate 6 x 12 Right', category: 'Plates Angled' },
  { id: '1126', name: 'Tile Round 1 x 2', category: 'Tiles Round and Curved' },
  { id: '1748', name: 'Tile Round 1 x 2 Half Circle', category: 'Tiles Round and Curved' },
  { id: '4150', name: 'Tile Round 2 x 2 with Bottom Cross', category: 'Tiles Round and Curved' },
  { id: '5520', name: 'Tile Round 2 x 2 Half Circle', category: 'Tiles Round and Curved' },
  { id: '7212', name: 'Tile Round 6 x 6', category: 'Tiles Round and Curved' },
  {
    id: '7836',
    name: 'Tile 2 x 2 Curved, Macaroni, Center Anti-Stud',
    category: 'Tiles Round and Curved',
  },
  {
    id: '14769',
    name: 'Tile Round 2 x 2 with Bottom Stud Holder',
    category: 'Tiles Round and Curved',
  },
  { id: '24246', name: 'Tile Round 1 x 1 Half Circle', category: 'Tiles Round and Curved' },
  { id: '25269', name: 'Tile Round 1 x 1 Quarter', category: 'Tiles Round and Curved' },
  { id: '27507', name: 'Tile 4 x 4 Curved, Macaroni', category: 'Tiles Round and Curved' },
  { id: '27925', name: 'Tile 2 x 2 Curved, Macaroni', category: 'Tiles Round and Curved' },
  { id: '39739', name: 'Tile 1 x 1 Heart', category: 'Tiles Round and Curved' },
  { id: '65474', name: 'Tile 6 x 8 with Rounded Corners', category: 'Tiles Round and Curved' },
  { id: '66857', name: 'Tile Round 2 x 4', category: 'Tiles Round and Curved' },
  { id: '67095', name: 'Tile Round 3 x 3', category: 'Tiles Round and Curved' },
  { id: '68869', name: 'Tile Round Corners 4 x 4 x 2/3', category: 'Tiles Round and Curved' },
  { id: '79393', name: 'Tile 3 x 3 Curved, Macaroni', category: 'Tiles Round and Curved' },
  { id: '98138', name: 'Tile Round 1 x 1', category: 'Tiles Round and Curved' },
];
